flowchart TD
  Start(["Start"])
  github_e2e_2891a341["github-e2e"]
  Start --> github_e2e_2891a341
  linear_e2e_decf3708["linear-e2e"]
  github_e2e_2891a341 --> linear_e2e_decf3708
  run_e2e_39efe696["run-e2e"]
  linear_e2e_decf3708 --> run_e2e_39efe696
  env_b77349bf["env"]
  run_e2e_39efe696 --> env_b77349bf
  resource_tracker_d95b6649["resource-tracker"]
  env_b77349bf --> resource_tracker_d95b6649
  vitest_e2e_config_4e2a61bc["vitest.e2e.config"]
  resource_tracker_d95b6649 --> vitest_e2e_config_4e2a61bc
  check_architecture_rules_6b7347fd["check-architecture-rules"]
  vitest_e2e_config_4e2a61bc --> check_architecture_rules_6b7347fd
  check_behavior_tests_2577f6be["check-behavior-tests"]
  check_architecture_rules_6b7347fd --> check_behavior_tests_2577f6be
  End(["End"])
  check_behavior_tests_2577f6be --> End
