/**
 * Diagram context renderers used by the init scaffold.
 *
 * This module owns diagram-refresh scaffold templates so `scaffold.ts` can
 * reference one stable interface instead of embedding long shell scripts.
 *
 * @module lib/init/scaffold-diagram-templates
 */

import { renderPackagedRootFile } from "./scaffold-root-templates.js";

/**
 * Load the packaged diagram context refresh script.
 *
 * @returns The UTF-8 contents of `scripts/refresh-diagram-context.sh`.
 */
export function renderRefreshDiagramContextScript(): string {
	return renderPackagedRootFile("scripts/refresh-diagram-context.sh");
}

/**
 * Load the packaged diagram freshness checker.
 *
 * @returns The UTF-8 contents of `scripts/check-diagram-freshness.sh`.
 */
export function renderCheckDiagramFreshnessScript(): string {
	return renderPackagedRootFile("scripts/check-diagram-freshness.sh");
}

/**
 * Render the initial agent-facing diagram context placeholder.
 *
 * @returns Markdown content written to `AI/context/diagram-context.md`.
 */
export function renderInitialDiagramContextTemplate(): string {
	return `# Diagram Context Pack

This file is auto-generated by the diagram-refresh CI job on every PR.

When source files change, the CI pipeline:
1. Runs \`@brainwav/diagram\` to generate Mermaid diagrams
2. Updates this file with current architecture
3. Commits changes back to the PR branch

## Usage for Agents

Reference this file to understand:
- Project structure and component relationships
- Module dependencies and data flows

- Database and ERD relationships emitted by \`@brainwav/diagram\`
- Test coverage patterns

Use this pack before opening raw source files. When you need TypeScript
implementation detail in this checkout, run:

\`\`\`bash
bash scripts/harness-cli.sh source-outline <path> --json
\`\`\`

Then unwrap one symbol at a time with \`--symbol <name>\`. Downstream repositories
can use \`harness source-outline <path>\`.


## Manual refresh

To refresh diagrams locally:

\`\`\`bash
# Install the tool
pnpm add -D @brainwav/diagram


# Preview context changes
bash scripts/refresh-diagram-context.sh --dry-run


# Generate diagrams
pnpm exec diagram all . --output-dir .diagram

# Update context

bash scripts/refresh-diagram-context.sh --force

# Verify generated manifest
jq '.generatedAt' .diagram/manifest.json >/dev/null

\`\`\`
`;
}

/**
 * Render the default diagram CLI config.
 *
 * @returns JSON content written to `.diagramrc`.
 */
export function renderDiagramRcTemplate(): string {
	return `{
	"ignore": ["node_modules", "dist", "coverage", "artifacts", ".git", ".diagram"]
}
`;
}
