/**
 * Template scaffold definitions for the init command.
 *
 * This module contains all template definitions that are rendered
 * when running `harness init` to scaffold a new project.
 *
 * @module lib/init/scaffold
 */

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
	DEFAULT_CI_PROVIDER_POLICY,
	DEFAULT_CONTRACT,
	NORTH_STAR_DECISION_QUESTION_SPECS,
	NORTH_STAR_PRIMARY_BOTTLENECK,
	NORTH_STAR_PRIMARY_METRIC,
} from "../contract/types.js";
import { formatRequiredChecksBulleted } from "../policy/required-checks.js";
import { PROJECT_MISE_REQUIRED_TOOLS } from "../policy/tooling-baseline.js";
import type { ProjectType } from "../project-type/types.js";
import { PROJECT_BRAIN_TEMPLATES } from "./project-brain-templates.js";
import {
	DEFAULT_CI_PROVIDER,
	getNormalizedRequiredChecks,
	isTemplateEnabledForProvider,
	renderCircleCIConfig,
	renderGitHubActionsPrPipelineWorkflow,
	renderReleasePrivateNpmWorkflow,
	renderRequiredChecksManifest,
	renderSecurityScanWorkflow,
	renderTransitionStatusArtifact,
} from "./scaffold-ci-templates.js";
import {
	CODEX_ENVIRONMENT_AUTOGENERATED_HEADER,
	renderCodexEnvironmentTemplate,
} from "./scaffold-codex-environment-templates.js";
import {
	renderCheckDiagramFreshnessScript,
	renderDiagramRcTemplate,
	renderInitialDiagramContextTemplate,
	renderRefreshDiagramContextScript,
} from "./scaffold-diagram-templates.js";
import {
	renderContributingTemplate,
	renderPrekConfigTemplate,
	renderPullRequestTemplate,
} from "./scaffold-doc-templates.js";
import { renderCheckEnvironmentScript } from "./scaffold-environment-templates.js";
import {
	renderChangelogTemplate,
	renderCodeRabbitTemplate,
	renderCodeownersTemplate,
	renderIssueTemplateConfig,
} from "./scaffold-governance-templates.js";
import {
	renderCheckHookCriticalConfigSyncScript,
	renderCheckStagedSecretsScript,
	renderSetupGitHooksScript,
	renderValidateCommitMsgScript,
} from "./scaffold-hook-templates.js";
import {
	CODESTYLE_PACK_TEMPLATE_FILES,
	renderCheckCodestyleParityScript,
	renderCheckDocStyleScript,
	renderCodestylePackTemplate,
	renderCodestyleTemplate,
	renderPackagedRootFile,
	renderValidateCodestyleScript,
} from "./scaffold-root-templates.js";
import {
	renderSemgrepBootstrapScript,
	renderSemgrepChangedScript,
	renderSemgrepFullScript,
	renderSemgrepPrePushRules,
} from "./scaffold-semgrep-templates.js";
import {
	renderAddPackageCommand,
	renderCodexEnforcedTemplate,
	renderCodexLearnTemplate,
	renderCodexPreflightLegacyLocalMemoryTemplate,
	renderCodexPreflightTemplate,
	renderHarnessCliWrapper,
	renderHarnessGateRunner,
	renderInstallCommand,
	renderLocalHarnessExecCommand,
	renderVerifyWorkScript,
} from "./scaffold-shell-templates.js";
import {
	renderNewTaskScript,
	renderPrepareWorktreeScript,
} from "./scaffold-worktree-templates.js";
import {
	type CIProvider,
	CODEX_ENVIRONMENT_TEMPLATE_PATH,
	CURRENT_SCHEMA_VERSION,
	type InitErrorOutput,
	type InitOptions,
	type PackageJsonLike,
	type Template,
	type TemplateRenderContext,
} from "./types.js";

// Re-export for convenience
export type { Template, TemplateRenderContext, CIProvider };
export { CODESTYLE_PACK_TEMPLATE_FILES };
export { isTemplateEnabledForProvider };

// === Local Constants ===

const AGENT_BRANCH_PREFIX = "codex";
const BIOME_SCHEMA_VERSION = "1.9.4";
const BIOME_SCHEMA_URL = `https://biomejs.dev/schemas/${BIOME_SCHEMA_VERSION}/schema.json`;

/**
 * Builds the shell command to invoke a package script using the given package manager.
 *
 * @param packageManager - Package manager identifier (e.g., "npm", "yarn", "pnpm"); when `"npm"` the returned command uses `npm run`
 * @param script - The script name to execute as defined in `package.json`
 * @returns The shell command string that runs the specified script with the selected package manager
 */
function renderScriptCommand(packageManager: string, script: string): string {
	if (packageManager === "npm") {
		return `npm run ${script}`;
	}
	return `${packageManager} ${script}`;
}

function shellEscapeArg(value: string): string {
	return `'${value.split("'").join(`'"'"'`)}'`;
}

/**
 * Constructs a package-manager-specific install command used during workflow bootstrap.
 *
 * @param packageManager - Package manager identifier (e.g., `"npm"`, `"pnpm"`, `"yarn"`).
 * @returns The install command string: `"npm ci"` when `packageManager` is `"npm"`, otherwise the package manager's install command with `--frozen-lockfile` appended.
 */
function renderWorkflowBootstrapInstallCommand(packageManager: string): string {
	if (packageManager === "npm") {
		return "npm ci";
	}
	return `${renderInstallCommand(packageManager)} --frozen-lockfile`;
}

function renderMemoryValidateCommand(): string {
	return `test -f memory.json && jq -e '.meta.version == "1.0" and (.preamble.bootstrap | type == "boolean") and (.preamble.search | type == "boolean") and (.entries | type == "array")' memory.json >/dev/null`;
}

/**
 * Escapes all RegExp metacharacters in a string so it can be used as a literal in a regular expression.
 *
 * @param value - The input string to escape
 * @returns The input with regex metacharacters (e.g., . * + ? ^ $ { } ( ) | [ ] \ ) prefixed by a backslash
 */
/**
 * Produce the repository-level `.npmrc` contents used by generated projects.
 *
 * The returned text contains recommended defaults for registry, lifecycle and peer-install behavior,
 * a commented note preserving pnpm's isolated linker as the default, and guidance that auth tokens
 * must be provided via user-level or CI-injected `.npmrc` rather than the repository file.
 *
 * @returns The `.npmrc` file contents to write into the scaffolded repository
 */
function renderDefaultNpmrc(): string {
	return `@brainwav:registry=https://registry.npmjs.org/
ignore-scripts=true
strict-peer-dependencies=false
auto-install-peers=false
shamefully-hoist=false
# Keep pnpm's isolated linker default; enable hoisted linker only for legacy-compat repos.
# node-linker=hoisted

# Auth should come from user-level ~/.npmrc or CI-injected ~/.npmrc, not this repo.
# Do not add //registry.npmjs.org/:_authToken=... here, because it can override
# a valid npm login and break local installs.
`;
}

/**
 * Read and parse a package.json file from a directory.
 *
 * @param targetDir - Directory to read `package.json` from
 * @returns The parsed `package.json` as `PackageJsonLike` if the file exists and contains a valid JSON object, `undefined` otherwise
 */
function readPackageJson(targetDir: string): PackageJsonLike | undefined {
	const packageJsonPath = resolve(targetDir, "package.json");
	if (!existsSync(packageJsonPath)) {
		return undefined;
	}

	try {
		const parsed = JSON.parse(
			readFileSync(packageJsonPath, "utf-8"),
		) as unknown;
		if (!parsed || typeof parsed !== "object") {
			return undefined;
		}
		return parsed as PackageJsonLike;
	} catch {
		return undefined;
	}
}

function readPackageScripts(targetDir: string): string[] {
	const parsed = readPackageJson(targetDir);
	const { scripts } = parsed ?? {};
	if (!scripts || typeof scripts !== "object") {
		return [];
	}
	return Object.entries(scripts)
		.filter(
			([name, value]) => typeof name === "string" && typeof value === "string",
		)
		.map(([name]) => name);
}

function readIssueTrackingUrl(targetDir: string): string | undefined {
	const parsed = readPackageJson(targetDir);
	if (!parsed) {
		return undefined;
	}
	const { bugs } = parsed;
	if (typeof bugs === "string") {
		return bugs.trim() || undefined;
	}
	if (bugs && typeof bugs === "object" && typeof bugs.url === "string") {
		const trimmed = bugs.url.trim();
		return trimmed || undefined;
	}
	return undefined;
}

function readProjectName(targetDir: string): string | undefined {
	const parsed = readPackageJson(targetDir);
	if (!parsed?.name || typeof parsed.name !== "string") {
		return undefined;
	}
	// Strip scope prefix if present (e.g., @brainwav/coding-harness -> coding-harness)
	const name = parsed.name.replace(/^@[^/]+\//, "").trim();
	return name || undefined;
}

function readRepoUrl(targetDir: string): string | undefined {
	const parsed = readPackageJson(targetDir);
	if (!parsed) {
		return undefined;
	}
	const { repository } = parsed;
	if (typeof repository === "string") {
		return normalizeRepoUrl(repository);
	}
	if (
		repository &&
		typeof repository === "object" &&
		typeof repository.url === "string"
	) {
		return normalizeRepoUrl(repository.url);
	}
	return undefined;
}

function normalizeRepoUrl(repositoryUrl: string): string | undefined {
	const trimmed = repositoryUrl.trim();
	if (!trimmed) {
		return undefined;
	}

	const withoutGitPrefix = trimmed.replace(/^git\+/, "");
	const withoutFragment = withoutGitPrefix.replace(/#[^#]+$/, "");
	const sshStyleMatch = withoutFragment.match(
		/^(?:ssh:\/\/)?git@([^/:]+)[:/]([^#]+)$/i,
	);
	if (sshStyleMatch) {
		const host = sshStyleMatch[1];
		const repoPath = sshStyleMatch[2]?.replace(/\.git$/, "");
		if (host && repoPath) {
			return `https://${host}/${repoPath}.git`;
		}
	}

	const shorthandPrefixMatch = withoutFragment.match(
		/^(github|gitlab|bitbucket):([^/][^#]+)$/i,
	);
	if (shorthandPrefixMatch) {
		const provider = shorthandPrefixMatch[1]?.toLowerCase();
		const repoPath = shorthandPrefixMatch[2]?.replace(/\.git$/, "");
		const host =
			provider === "github"
				? "github.com"
				: provider === "gitlab"
					? "gitlab.com"
					: "bitbucket.org";
		return `https://${host}/${repoPath}.git`;
	}

	const bareGithubShorthandMatch = withoutFragment.match(
		/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/,
	);
	if (bareGithubShorthandMatch) {
		return `https://github.com/${withoutFragment.replace(/\.git$/, "")}.git`;
	}

	return withoutFragment || undefined;
}

function extractLinearProjectSlug(
	issueTrackingUrl: string | undefined,
): string | undefined {
	if (!issueTrackingUrl) {
		return undefined;
	}
	// Match patterns like https://linear.app/jscraik/project/coding-harness-bb735dbbda79
	const match = issueTrackingUrl.match(
		/linear\.app\/[^/]+\/project\/([a-z0-9-]+)/i,
	);
	return match?.[1] ?? undefined;
}

/**
 * Detect package manager from lock files.
 * Returns the package manager based on which lock file exists.
 */
export function detectPackageManager(dir: string): "pnpm" | "yarn" | "npm" {
	if (existsSync(resolve(dir, "pnpm-lock.yaml"))) return "pnpm";
	if (existsSync(resolve(dir, "yarn.lock"))) return "yarn";
	if (existsSync(resolve(dir, "package-lock.json"))) return "npm";
	return "npm";
}

/**
 * Normalize and validate a CI provider identifier.
 *
 * @param value - The provider identifier to normalize; may be `undefined` or an empty string to use the default.
 * @returns `ok: true` with `value` set to the normalized provider (`github-actions` or `circleci`), or `ok: false` with an `INVALID_PATH` error describing unsupported values.
 */
export function normalizeCIProvider(
	value: string | undefined,
): { ok: true; value: CIProvider } | { ok: false; error: InitErrorOutput } {
	if (!value || value.trim().length === 0) {
		return { ok: true, value: DEFAULT_CI_PROVIDER };
	}

	if (value === "github-actions" || value === "circleci") {
		return { ok: true, value };
	}

	return {
		ok: false,
		error: {
			code: "INVALID_PATH",
			message: `Unsupported CI provider: ${value}. Expected one of: github-actions, circleci.`,
		},
	};
}

/**
 * Construct a TemplateRenderContext populated from repository metadata and selected init options.
 *
 * The returned context includes discovered values (package scripts, project name, repo URL, issue tracker URL)
 * when available, a `securityEmail` resolved from the `HARNESS_SECURITY_EMAIL` environment variable or
 * `"security@example.com"` as a fallback, and any explicitly provided `ciProvider` or `projectType`.
 * If `options.issueTracker` is `"none"` or `"github"`, `linearProjectSlug` will be omitted.
 *
 * @param targetDir - Filesystem path of the repository to inspect for package and repository metadata
 * @param ciProvider - Optional CI provider to include in the context
 * @param projectType - Optional project type hint to include in the context
 * @param options - Init options that can toggle returned flags (e.g., setting `minimal` or `issueTracker`)
 * @returns A TemplateRenderContext containing discovered metadata and applied init options; fields that
 * are not discoverable or explicitly suppressed are omitted.
 */
export function createTemplateRenderContext(
	targetDir: string,
	ciProvider?: CIProvider,
	projectType?: ProjectType,
	options?: InitOptions,
): TemplateRenderContext {
	const issueTrackingUrl = readIssueTrackingUrl(targetDir);
	const projectName = readProjectName(targetDir);
	const repoUrl = readRepoUrl(targetDir);
	let linearProjectSlug = extractLinearProjectSlug(issueTrackingUrl);

	// Solo orchestration overrides
	if (options?.issueTracker === "none" || options?.issueTracker === "github") {
		// Suppress linear project slug if an alternative tracker or 'none' is explicitly requested
		linearProjectSlug = undefined;
	}

	// Resolve security contact email: env var override, then safe fallback value
	const securityEmail =
		process.env.HARNESS_SECURITY_EMAIL ?? "security@example.com";
	return {
		targetDir,
		...(ciProvider ? { ciProvider } : {}),
		packageScripts: readPackageScripts(targetDir),
		...(issueTrackingUrl ? { issueTrackingUrl } : {}),
		...(projectName ? { projectName } : {}),
		...(repoUrl ? { repoUrl } : {}),
		...(linearProjectSlug ? { linearProjectSlug } : {}),
		...(projectType ? { projectType } : {}),
		securityEmail,
		...(options?.minimal ? { minimal: true } : {}),
		...(options?.issueTracker ? { issueTracker: options.issueTracker } : {}),
	};
}

function isAutogeneratedCodexEnvironment(path: string): boolean {
	if (!existsSync(path)) {
		return false;
	}

	try {
		const firstLine = readFileSync(path, "utf-8").split("\n", 1)[0] ?? "";
		return firstLine.trim() === CODEX_ENVIRONMENT_AUTOGENERATED_HEADER;
	} catch {
		return false;
	}
}

/**
 * Decide whether an existing scaffold target is safe to update automatically.
 *
 * Only autogenerated Codex environment files are auto-updated because they carry
 * an explicit generated-file header and are owned by the harness scaffold.
 */
export function shouldAutoUpdateTemplate(
	templatePath: string,
	targetPath: string,
): boolean {
	if (templatePath !== CODEX_ENVIRONMENT_TEMPLATE_PATH) {
		return false;
	}
	return isAutogeneratedCodexEnvironment(targetPath);
}

/**
 * Extract the version from a biome $schema URL.
 * e.g. "https://biomejs.dev/schemas/1.9.4/schema.json" → "1.9.4"
 */
function extractBiomeSchemaVersion(schemaUrl: string): string | undefined {
	const match = schemaUrl.match(/\/schemas\/([0-9]+\.[0-9]+\.[0-9]+)\//);
	return match?.[1];
}

/**
 * Read the $schema version from an existing biome.json.
 * Returns undefined if the file can't be parsed or has no $schema.
 */
function readExistingBiomeVersion(targetPath: string): string | undefined {
	try {
		const content = readFileSync(targetPath, "utf-8");
		const parsed = JSON.parse(content) as unknown;
		if (!parsed || typeof parsed !== "object") return undefined;
		const schema = (parsed as Record<string, unknown>).$schema;
		if (typeof schema !== "string") return undefined;
		return extractBiomeSchemaVersion(schema);
	} catch {
		return undefined;
	}
}

/**
 * JSC-57: Version-aware decision for tooling config files during init.
 *
 * Returns:
 *  - "skip"         — existing version is newer or equal to template; don't overwrite
 *  - "force_update" — existing version is older than template; upgrade it
 *  - "no_opinion"   — not a versioned tooling file, or file doesn't exist
 */
export function getToolingVersionDecision(
	templatePath: string,
	targetPath: string,
): "skip" | "force_update" | "no_opinion" {
	if (templatePath !== "biome.json") return "no_opinion";
	if (!existsSync(targetPath)) return "no_opinion";

	const existingVersion = readExistingBiomeVersion(targetPath);
	if (!existingVersion) return "no_opinion";

	// Semver comparison without external deps
	const templateParts = BIOME_SCHEMA_VERSION.split(".").map(Number);
	const existingParts = existingVersion.split(".").map(Number);

	for (let i = 0; i < 3; i++) {
		const t = templateParts[i] ?? 0;
		const e = existingParts[i] ?? 0;
		if (e > t) return "skip"; // existing is newer — don't downgrade
		if (e < t) return "force_update"; // existing is older — upgrade
	}
	return "skip"; // versions equal — already up to date
}

/**
 * Preserve the legacy boolean API used by interactive init flows.
 *
 * @returns `true` when the target tooling config is newer than the scaffold
 * template and should not be downgraded.
 */
export function shouldSkipDueToNewerToolingVersion(
	templatePath: string,
	targetPath: string,
): boolean {
	const decision = getToolingVersionDecision(templatePath, targetPath);
	return decision === "skip";
}

/**
 * Produce a Symphony workflow configuration and accompanying human-readable workflow document tailored to the repository.
 *
 * @param pm - Package manager identifier (e.g., `"npm"`, `"yarn"`, `"pnpm"`) used to choose install and command wrappers embedded in the workflow.
 * @param context - Template render context whose fields (notably `linearProjectSlug`, `projectName`, `repoUrl`, and `issueTracker`) populate tracker configuration, repository bootstrap commands, and workflow metadata.
 * @returns The complete workflow file content as a string: a Symphony YAML configuration section followed by an extensive Markdown workflow document with states, transition table, error handling, and validation checklist.
 */
function renderWorkflowTemplate(
	pm: string,
	context: TemplateRenderContext,
): string {
	const projectSlug = context.linearProjectSlug || "<your-project-slug>";
	const projectName = context.projectName || "<project-name>";
	const repoUrl = context.repoUrl || "$SOURCE_REPO_URL";
	const trackerKind = context.issueTracker ?? "linear";
	const renderedRepoUrl =
		repoUrl === "$SOURCE_REPO_URL" ? repoUrl : shellEscapeArg(repoUrl);
	const installCommand = renderWorkflowBootstrapInstallCommand(pm);
	const checkCommand = renderScriptCommand(pm, "check");
	const trackerBlock =
		trackerKind === "linear"
			? `tracker:
  kind: linear
  api_key: $LINEAR_API_KEY
  project_slug: "${projectSlug}"
  active_states:
    - Todo
    - In Progress
  terminal_states:
    - Done
    - Canceled
    - Duplicate`
			: trackerKind === "github"
				? `tracker:
  kind: github
  active_states:
    - OPEN
  terminal_states:
    - MERGED
    - CLOSED`
				: `tracker:
  kind: none`;
	const transitionRows =
		trackerKind === "linear"
			? `| \`S0 TODO\` | \`claim\` | preflight passes | \`harness linear claim --issue <LK> --branch <codex/...>\` | \`S1 IN_PROGRESS\` |
| \`S1 IN_PROGRESS\` | \`advance\` | \`${checkCommand}\` passes | \`harness linear handoff --issue <LK> --pr-url <url> --evidence-urls <url>\` | \`S2 IN_REVIEW\` |
| \`S1 IN_PROGRESS\` | \`blocked\` | dependency unavailable | emit unblock payload | \`S4 BLOCKED\` |
| \`S1 IN_PROGRESS\` | \`error\` | unrecoverable runtime/policy issue | record failure artifact | \`S5 FAIL\` |
| \`S2 IN_REVIEW\` | \`approved\` | review and CI pass | \`harness linear close --issue <LK> --pr-url <url>\` | \`S3 DONE\` |
| \`S2 IN_REVIEW\` | \`rejected\` | review gate fails | route back to working | \`S1 IN_PROGRESS\` |
| \`S4 BLOCKED\` | \`unblocked\` | dependency restored | resume execution | \`S1 IN_PROGRESS\` |`
			: `| \`S0 TODO\` | \`claim\` | preflight passes | create branch/worktree and start implementation | \`S1 IN_PROGRESS\` |
| \`S1 IN_PROGRESS\` | \`advance\` | \`${checkCommand}\` passes | open PR and attach validation evidence | \`S2 IN_REVIEW\` |
| \`S1 IN_PROGRESS\` | \`blocked\` | dependency unavailable | emit unblock payload | \`S4 BLOCKED\` |
| \`S1 IN_PROGRESS\` | \`error\` | unrecoverable runtime/policy issue | record failure artifact | \`S5 FAIL\` |
| \`S2 IN_REVIEW\` | \`approved\` | review and CI pass | merge PR and record closeout evidence | \`S3 DONE\` |
| \`S2 IN_REVIEW\` | \`rejected\` | review gate fails | route back to working | \`S1 IN_PROGRESS\` |
| \`S4 BLOCKED\` | \`unblocked\` | dependency restored | resume execution | \`S1 IN_PROGRESS\` |`;

	return `---
# Symphony Workflow Configuration
# Generated by harness init — customize values below for your project.
${trackerBlock}
workspace:
  root: $SYMPHONY_WORKSPACE_ROOT
hooks:
  after_create: |
    git clone --depth 1 ${renderedRepoUrl} .
    ${installCommand}
    if ! mise trust --yes .mise.toml >/dev/null 2>&1; then
      echo "[symphony] failed to trust .mise.toml"
      echo "[symphony] Fix: run 'mise trust --yes .mise.toml' and retry"
      exit 1
    fi
    mise_trust_status="$(mise trust --show .mise.toml 2>/dev/null || true)"
    if [[ "$mise_trust_status" != *": trusted"* ]]; then
      echo "[symphony] mise config is not trusted"
      echo "[symphony] Fix: run 'mise trust --yes .mise.toml' and retry"
      exit 1
    fi
  after_run: |
    cd "$WORKSPACE" && rm -rf node_modules
agent:
  max_concurrent_agents: 3
  max_turns: 12
codex:
  command: "\${CODEX_BIN:-codex} app-server"
  approval_policy: on-request
  thread_sandbox: workspace-write
---

# ${projectName} Workflow

## Table of Contents
- [Abbreviations](#abbreviations)
- [Metadata](#metadata)
- [Invariants](#invariants)
- [States](#states)
- [Transition Table (Canonical)](#transition-table-canonical)
- [Error Handling](#error-handling)
- [Idempotency](#idempotency)
- [Execution Modes](#execution-modes)
- [Dry-Run Simulation](#dry-run-simulation)
- [Observability Logs](#observability-logs)
- [Validation Checklist](#validation-checklist)

## Abbreviations
| Abbr | Meaning |
| --- | --- |
| \`S\` | state |
| \`E\` | event |
| \`G\` | guard |
| \`A\` | action |
| \`N\` | next state |

## Metadata
| Field | Value |
| --- | --- |
| \`owner\` | <owner> |
| \`max_duration\` | 60m |
| \`escalation\` | <escalation-path> |
| \`change_class\` | behavior |

## Invariants
| Field | Value |
| --- | --- |
| \`test_mode\` | tdd-required |
| \`test_tier\` | integration |
| \`tracer_bullet_first\` | yes |
| \`red_evidence_required\` | yes |

## States
\`\`\`txt
S0 TODO (non-terminal)
S1 IN_PROGRESS (non-terminal)
S2 IN_REVIEW (non-terminal)
S3 DONE (terminal)
S4 BLOCKED (non-terminal)
S5 FAIL (terminal)
\`\`\`

## Transition Table (Canonical)
\`S | E | G | A | N\`

| S | E | G | A | N |
| --- | --- | --- | --- | --- |
${transitionRows}

## Error Handling
- \`VALIDATION_ERROR\`: invalid input, malformed data, or missing required fields.
- \`BLOCKED_DEPENDENCY\`: missing auth/secret/permission; route to BLOCKED.
- \`POLICY_FAIL\`: required checks, policy, or gate failures.
- \`SYSTEM_ERROR\`: CLI/runtime/network failure; emit failed command.

## Idempotency
- Idempotency key: \`{{workflow_id}}|{{event}}|{{from_state}}|{{correlation_id}}\`.
- Replayed events with same key must no-op or upsert only.
- Side effects must be guarded against duplication.

## Execution Modes
- \`STRICT\`: hard-fail on validation/policy violations.
- \`ADVISORY\`: emit warnings and continue for non-safety violations.

## Dry-Run Simulation
- Dry-run has no side effects.
- Dry-run emits deterministic transition trace output.
- Output includes selected transition row and guard evaluation.

## Observability Logs
\`\`\`json
{
  "workflow_id": "{{WORKFLOW_ID}}",
  "transition_code": "S0:claim",
  "from_state": "S0 TODO",
  "to_state": "S1 IN_PROGRESS",
  "correlation_id": "{{CORRELATION_FORMAT}}",
  "result": "success|blocked|failed"
}
\`\`\`

## Validation Checklist
- [ ] canonical \`S | E | G | A | N\` table exists
- [ ] 5 non-empty cells in each transition row
- [ ] all required error codes are present
- [ ] \`STRICT\` and \`ADVISORY\` modes are declared
- [ ] dry-run semantics include no side effects and deterministic trace output
- [ ] required observability log fields are present
- [ ] \`change_class\` metadata is declared
- [ ] validation contract fields are declared
- [ ] behavior-changing workflows include TDD or reviewed exemption metadata
- [ ] tracker-specific workflow actions are wired into transition actions
`;
}

function renderScaffoldNorthStar(
	context: TemplateRenderContext,
): NonNullable<typeof DEFAULT_CONTRACT.northStar> {
	const projectName = context.projectName?.trim() || "This repository";
	return {
		mission: `${projectName} uses Coding Harness to reduce PR lead time while preserving safe, evidence-backed human oversight.`,
		primaryMetric: NORTH_STAR_PRIMARY_METRIC,
		primaryBottleneck: NORTH_STAR_PRIMARY_BOTTLENECK,
		autonomyBoundary:
			"Low and medium-risk changes may be automated when evidence is deterministic and rollback remains explicit; high-risk changes remain human-mediated.",
		safetyFloor: [
			"deterministic evidence over intuition",
			"strict current-head SHA discipline",
			"bounded auto-remediation instead of open-ended write access",
			"explicit rollback paths for higher-risk automation",
			"independent review surfaces that do not collapse back into self-approval",
		],
		nonGoals: [
			"governance surface area as a proxy for progress",
			"feature count without measurable throughput or reliability benefit",
			"manual coordination steps that recur every run or every PR",
			"broad autonomy expansion without evidence that the review or rework loop got cheaper",
		],
		decisionQuestions: NORTH_STAR_DECISION_QUESTION_SPECS.map((question) => ({
			id: question.id,
			prompt: question.prompt,
		})),
	};
}

function renderScaffoldProductSurface(): NonNullable<
	typeof DEFAULT_CONTRACT.productSurface
> {
	return {
		surfaces: [
			{
				surfaceId: "automation-control-plane",
				surfaceType: "policy",
				class: "core",
				owner: "maintainers",
				northStarContribution:
					"Keeps delivery automation aligned to PR lead-time outcomes.",
				manualGlueReductionClaim:
					"Converts recurring reviewer reminders into explicit policy checks.",
				reliabilityContribution:
					"Centralizes automation guardrails in one deterministic contract surface.",
				evidenceReference: "harness.contract.json",
				ownedPaths: ["harness.contract.json"],
				lastReviewedAt: "2026-04-22",
			},
		],
	};
}

function renderScaffoldOverrideReviewerRegistry(
	context: TemplateRenderContext,
): NonNullable<typeof DEFAULT_CONTRACT.overrideReviewerRegistry> {
	const projectName = context.projectName?.trim() || "Project";
	return {
		trustedReviewers: [
			{
				reviewerId: "project-maintainers",
				reviewerType: "team",
				signatureRef: "refs/reviewers/project-maintainers",
				displayName: `${projectName} Maintainers`,
				status: "active",
			},
		],
	};
}

export const TEMPLATES: Template[] = [
	{
		path: "harness.contract.json",
		render: (pm, context) =>
			JSON.stringify(
				{
					version: CURRENT_SCHEMA_VERSION,
					riskTierRules: {
						"src/auth/**": "high",
						"src/api/**": "high",
						"src/lib/**": "medium",
						"**/*.test.ts": "low",
					},
					mergePolicy: {
						high: ["review-gate", "evidence-verify"],
						medium: ["review-gate"],
						low: [],
					},
					docsDriftRules: {},
					branchProtection: {
						requiredChecks: [
							...getNormalizedRequiredChecks(
								context.ciProvider ?? DEFAULT_CI_PROVIDER,
								context,
							),
						],
						restrictDeletions: true,
						blockForcePushes: true,
						requireLinearHistory: true,
						requirePullRequest: true,
						requiredApprovingReviewCount: 1,
						dismissStaleReviewsOnPush: true,
						requireConversationResolution: true,
						requireCodeOwnerReview: false,
						requireLastPushApproval: false,
						requireBranchesUpToDate: true,
						allowedMergeMethods: {
							mergeCommit: true,
							squash: true,
							rebase: true,
						},
						codeQuality: {
							required: true,
							severity: "all",
						},
						publicCodeScanning: {
							required: true,
							publicOnly: true,
							tool: "CodeQL",
							alertsThreshold: "errors",
							securityAlertsThreshold: "high_or_higher",
						},
					},
					toolingPolicy: DEFAULT_CONTRACT.toolingPolicy,
					...(context.issueTracker === "github" ||
					context.issueTracker === "none"
						? {}
						: {
								issueTrackingPolicy: {
									provider: "linear" as const,
									...(context.issueTrackingUrl
										? { projectUrl: context.issueTrackingUrl }
										: {}),
									requirePackageBugsUrl: true,
									disableGitHubIssues: true,
									requireBranchIssueKey: true,
									requirePrIssueKey: true,
									prReferenceMode: "either" as const,
									branchPrefix: AGENT_BRANCH_PREFIX,
								},
							}),
					evidencePolicy: {
						requiredFor: [],
						allowedTypes: ["png", "jpeg"],
						maxFileSizeBytes: 1048576,
					},
					northStar: renderScaffoldNorthStar(context),
					productSurface: renderScaffoldProductSurface(),
					overrideReviewerRegistry:
						renderScaffoldOverrideReviewerRegistry(context),
					diffBudget: {
						maxFiles: 10,
						maxNetLOC: 400,
						overrideLabel: "diff-budget-override",
					},
					uiLoopPolicy: {
						fastCommand: renderScriptCommand(pm, "ui:fast"),
						verifyCommand: renderScriptCommand(pm, "ui:verify"),
						exploreCommand: renderScriptCommand(pm, "ui:explore"),
						sloTargets: {
							fastLoopSeconds: 30,
							verifyLoopSeconds: 120,
						},
					},
					runtimePolicy: {
						nodeVersion: "24.x",
						createIssueOnAgentFindings: true,
					},
					memoryPolicy: {
						enabled: true,
						provider: "local",
						sessionIdTemplate: "repo:<name>:task:<id>",
						domain: "default",
						requiredTags: ["repo", "area", "type"],
						maxObservationsPerStep: 3,
						allowedLevels: ["observation", "learning", "pattern"],
						requireStartRead: true,
						requireCloseoutSummary: true,
						forbiddenContentPatterns: [
							"token",
							"api[_-]?key",
							"secret",
							"password",
							"credential",
						],
					},
					memoryMaintenancePolicy: {
						validateSchedule: "weekly",
						reflectSchedule: "weekly",
						questionSlaDays: 7,
						duplicateThreshold: 0.8,
					},
					memoryEvalPolicy: {
						trialsPerTask: 3,
						requiredMetrics: ["pass^k", "tool_errors", "duplicate_rate"],
						passPowKThreshold: 0.8,
					},
					observabilityPolicy: {
						provider: "logs",
						collectorEndpoint: "http://localhost:4318",
					},
					packageManagerPolicy: {
						allowedManagers: ["pnpm", "npm", "yarn"],
						requiredManager: null,
					},
					remediationPolicy: {
						providerDefaults: {
							codex: {
								autoApplyMaxTier: "medium",
								dryRunOnlyByDefault: false,
							},
						},
						marker: "[auto-remediate]",
						timeoutMinutes: 10,
						retryLimit: 3,
						requireEvidence: true,
					},
					loopStageContracts: {
						"risk-policy-gate": {
							inputs: ["changed_files", "harness.contract.json"],
							outputs: ["risk-policy-gate.result"],
							schema: "loop-stage-contract/v1",
							failPolicy: "fail_closed" as const,
							if: "always()",
							permissions: ["contents:read", "pull-requests:read"],
							timeoutMinutes: 15,
							concurrency: "none",
						},
						"review-gate": {
							inputs: [
								"risk-policy-gate.result",
								"head_sha",
								"harness.contract.json",
							],
							outputs: ["review-gate.result"],
							schema: "loop-stage-contract/v1",
							failPolicy: "fail_closed" as const,
							if: "always()",
							permissions: ["contents:read", "pull-requests:read"],
							timeoutMinutes: 15,
							concurrency: "none",
						},
						"evidence-verify": {
							inputs: [
								"review-gate.result",
								"evidence_files",
								"harness.contract.json",
							],
							outputs: ["evidence-verify.result", "browser-evidence-artifacts"],
							schema: "loop-stage-contract/v1",
							failPolicy: "fail_closed" as const,
							if: "always()",
							permissions: ["contents:read"],
							timeoutMinutes: 15,
							concurrency: "none",
						},
						"remediation-decision": {
							inputs: [
								"evidence-verify.result",
								"findings.json",
								"harness.contract.json",
							],
							outputs: [
								"remediation-decision.result",
								"remediation-decision-artifacts",
							],
							schema: "loop-stage-contract/v1",
							failPolicy: "fail_closed" as const,
							if: "always()",
							permissions: ["contents:read", "pull-requests:write"],
							timeoutMinutes: 15,
							concurrency: "none",
						},
					},
					pilotGapCasePolicy: {
						enabled: false,
						defaultSlaHours: 72,
						requireClosureEvidence: true,
						storePath: ".harness/gap-cases.v1.json",
					},
					pilotRollbackPolicy: {
						autoTrigger: true,
						requireManualRelease: true,
						completionMarkerPath: ".harness/rollback-marker.json",
						mode: "manual" as const,
					},
					pilotAuthzPolicy: {
						githubScopeAllowlist: [
							"pull_requests:write",
							"contents:read",
							"issues:write",
						],
						repoAllowlist: [],
						branchAllowlist: [],
						protectedBranchDenylist: ["main", "master", "release/*"],
						enforceBranchProtection: true,
					},
					controlPlanePolicy: {
						overridePolicy: {
							authorizedPrincipals: [],
							dualApprovalScopes: ["temporary_unblock", "temporary_promote"],
							maxTtlHours: 24,
							nonOverridableControls: [
								"canonical_runtime_invalid",
								"governance_trust_mismatch",
								"missing_required_instruction_surface",
								"missing_snapshot_integrity_verification",
							],
						},
					},
					ciProviderPolicy: {
						...DEFAULT_CI_PROVIDER_POLICY,
						activeProvider:
							context.ciProvider ?? DEFAULT_CI_PROVIDER_POLICY.activeProvider,
					},
					contextIntegrityPolicy: DEFAULT_CONTRACT.contextIntegrityPolicy,
					...(context.projectType !== undefined
						? { projectType: context.projectType }
						: {}),
				},
				null,
				2,
			),
	},
	{
		path: "memory.json",
		render: () =>
			JSON.stringify(
				{
					repo: "replace-with-repo-name",
					session_id: "bootstrap/init",
					preamble: {
						bootstrap: true,
						search: true,
					},
					entries: [
						{
							level: "observation",
							content:
								"Harness memory baseline initialized. Replace with task-specific observations.",
							tags: ["repo:unknown", "area:bootstrap", "type:setup"],
							session_id: "bootstrap/init",
							source: "harness init",
							observed_at: "2026-01-01T00:00:00.000Z",
						},
					],
					closeout: {
						forjamie_updated: false,
						date: "2026-01-01T00:00:00.000Z",
					},
					meta: {
						created_at: "2026-01-01T00:00:00.000Z",
						version: "1.0",
					},
				},
				null,
				2,
			),
	},
	{
		path: ".harness/ci-required-checks.json",
		render: (_pm, context) =>
			renderRequiredChecksManifest(
				context.ciProvider ?? DEFAULT_CI_PROVIDER,
				context,
			),
	},
	{
		path: ".harness/ci-provider-transition-status.json",
		render: () => renderTransitionStatusArtifact(),
	},
	...PROJECT_BRAIN_TEMPLATES,
	{
		path: ".npmrc",
		render: () => renderDefaultNpmrc(),
	},
	{
		path: ".coderabbit.yaml",
		render: () => renderCodeRabbitTemplate(),
	},
	{
		path: "CHANGELOG.md",
		render: () => renderChangelogTemplate(),
	},
	{
		path: ".github/workflows/release-private-npm.yml",
		render: (pm) =>
			renderReleasePrivateNpmWorkflow({
				packageManager: pm,
				installCommand: renderWorkflowBootstrapInstallCommand(pm),
				checkCommand: renderScriptCommand(pm, "check"),
				buildCommand: renderScriptCommand(pm, "build"),
			}),
	},
	{
		path: ".github/workflows/pr-pipeline.yml",
		render: (pm, context) =>
			renderGitHubActionsPrPipelineWorkflow({
				installCommand: renderInstallCommand(pm),
				lintCommand: renderScriptCommand(pm, "lint"),
				typecheckCommand: renderScriptCommand(pm, "typecheck"),
				testCommand: renderScriptCommand(pm, "test:ci"),
				auditCommand: renderScriptCommand(pm, "audit"),
				checkCommand: renderScriptCommand(pm, "check"),
				memoryValidateCommand: renderMemoryValidateCommand(),
				linearTrackingEnabled:
					context.issueTracker !== "github" && context.issueTracker !== "none",
			}),
	},
	{
		path: ".github/workflows/secret-scan.yml",
		render: () => renderSecurityScanWorkflow(),
	},
	{
		path: ".circleci/config.yml",
		render: (pm, context) =>
			renderCircleCIConfig({
				packageManager: pm,
				installCommand:
					pm === "pnpm"
						? "pnpm install --frozen-lockfile --prefer-offline"
						: renderWorkflowBootstrapInstallCommand(pm),
				lintCommand: renderScriptCommand(pm, "lint"),
				typecheckCommand: renderScriptCommand(pm, "typecheck"),
				testCommand: renderScriptCommand(pm, "test:ci"),
				auditCommand: renderScriptCommand(pm, "audit"),
				checkCommand: renderScriptCommand(pm, "check"),
				dependencyAuditCommand: renderScriptCommand(pm, "audit:strict"),
				memoryValidateCommand: renderMemoryValidateCommand(),
				linearTrackingEnabled:
					context.issueTracker !== "github" && context.issueTracker !== "none",
			}),
	},
	{
		path: "CONTRIBUTING.md",
		render: (pm, context) => {
			const checkCommand = renderScriptCommand(pm, "check");
			const codestyleCommand = "bash scripts/validate-codestyle.sh";
			const memoryValidateCommand = renderMemoryValidateCommand();
			const requiredChecksList = formatRequiredChecksBulleted(
				getNormalizedRequiredChecks(
					context.ciProvider ?? DEFAULT_CI_PROVIDER,
					context,
				),
				"  - ",
			);
			const isCircleCI =
				(context.ciProvider ?? DEFAULT_CI_PROVIDER) === "circleci";
			return renderContributingTemplate({
				addCommand: renderAddPackageCommand(pm, "@brainwav/coding-harness"),
				agentBranchPrefix: AGENT_BRANCH_PREFIX,
				checkCommand,
				codestyleCommand,
				installCommand: renderInstallCommand(pm),
				isCircleCI,
				localExecCommand: renderLocalHarnessExecCommand(pm),
				memoryValidateCommand,
				requiredChecksList,
			});
		},
	},
	{
		path: ".github/PULL_REQUEST_TEMPLATE.md",
		render: (pm) => {
			const checkCommand = renderScriptCommand(pm, "check");
			const codestyleCommand = "bash scripts/validate-codestyle.sh";
			const memoryValidateCommand = renderMemoryValidateCommand();
			return renderPullRequestTemplate({
				checkCommand,
				codestyleCommand,
				memoryValidateCommand,
			});
		},
	},
	{
		path: "scripts/validate-commit-msg.js",
		render: () => renderValidateCommitMsgScript(AGENT_BRANCH_PREFIX),
	},
	{
		path: "scripts/setup-git-hooks.js",
		render: () => renderSetupGitHooksScript(),
	},
	{
		path: "scripts/check-staged-secrets.sh",
		render: () => renderCheckStagedSecretsScript(),
	},
	{
		path: "scripts/check-hook-critical-config-sync.sh",
		render: () => renderCheckHookCriticalConfigSyncScript(),
	},
	{
		path: "scripts/check-doc-style.sh",
		render: () => renderCheckDocStyleScript(),
	},
	{
		path: "scripts/check-related-tests.sh",
		render: () => renderPackagedRootFile("scripts/check-related-tests.sh"),
	},
	{
		path: "scripts/check-public-api-docs.mjs",
		render: () => renderPackagedRootFile("scripts/check-public-api-docs.mjs"),
	},
	{
		path: "scripts/check-code-size.mjs",
		render: () => renderPackagedRootFile("scripts/check-code-size.mjs"),
	},
	{
		path: "scripts/lib/changed-files.mjs",
		render: () => renderPackagedRootFile("scripts/lib/changed-files.mjs"),
	},
	{
		path: "scripts/check-semgrep-changed.sh",
		render: () => renderSemgrepChangedScript(),
	},
	{
		path: "scripts/check-semgrep-full.sh",
		render: () => renderSemgrepFullScript(),
	},
	{
		path: "scripts/semgrep-bootstrap.sh",
		render: () => renderSemgrepBootstrapScript(),
	},
	{
		path: "scripts/semgrep-pre-push.yml",
		render: () => renderSemgrepPrePushRules(),
	},
	{
		path: "scripts/refresh-diagram-context.sh",
		render: renderRefreshDiagramContextScript,
	},
	{
		path: "scripts/check-diagram-freshness.sh",
		render: renderCheckDiagramFreshnessScript,
	},
	{
		path: ".diagram/.gitkeep",
		render: () => "",
	},
	{
		path: "AI/context/diagram-context.md",
		render: renderInitialDiagramContextTemplate,
	},
	{
		path: ".diagramrc",
		render: renderDiagramRcTemplate,
	},
	{
		path: "biome.json",
		render: () => `{
	"$schema": "${BIOME_SCHEMA_URL}",
	"vcs": {
		"enabled": true,
		"clientKind": "git",
		"useIgnoreFile": true,
		"defaultBranch": "main"
	},
	"files": {
		"ignoreUnknown": true,
		"ignore": [
			"node_modules",
			"dist",
			"coverage",
			"artifacts"
		]
	},
	"overrides": [
		{
			"include": ["*.config.ts", "vite.config.ts", "vitest.config.ts"],
			"linter": {
				"rules": {
					"style": {
						"noDefaultExport": "off"
					}
				}
			}
		}
	],
	"linter": {
		"enabled": true,
		"rules": {
			"recommended": true,
			"correctness": {
				"noUnusedImports": "error",
				"noUnusedVariables": "error"
			},
			"suspicious": {
				"noEmptyBlockStatements": "error",
				"noExplicitAny": "warn",
				"noConsoleLog": "warn",
				"noDebugger": "error"
			},
			"style": {
				"noDefaultExport": "error",
				"useConst": "error",
				"useImportType": "error"
			}
		}
	},
	"organizeImports": {
		"enabled": true
	}
}
`,
	},
	{
		path: ".gitleaks.toml",
		render: () => `title = "Project gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Allowlist for test fixtures and examples."
paths = [
  "(^|/)docs?/",
  "(^|/)examples?/",
  "(^|/)test/",
  "(^|/)tests?/",
  "(^|/)spec/",
  "(^|/)__tests__/",
  "(^|/)test-data/",
  "(^|/)[^.]+\\\\.(test|spec)\\\\.[^.]+$",
]
regexes = [
  "\\\\[REDACTED\\\\]",
]
`,
	},
	{
		path: "prek.toml",
		render: () => renderPrekConfigTemplate(),
	},
	{
		path: ".mise.toml",
		render: () => `[tools]
${PROJECT_MISE_REQUIRED_TOOLS.map(([tool, version]) => `"${tool}" = "${version}"`).join("\n")}

[env]
CLAUDE_APPROVAL_POSTURE = "require"
`,
	},
	{
		path: "CODESTYLE.md",
		render: () => renderCodestyleTemplate(),
	},
	...CODESTYLE_PACK_TEMPLATE_FILES.map((path) => ({
		path,
		render: () => renderCodestylePackTemplate(path),
	})),
	{
		path: "scripts/codex-preflight.sh",
		render: () => renderCodexPreflightTemplate(),
	},
	{
		path: "scripts/codex-preflight-local-memory-legacy.sh",
		render: () => renderCodexPreflightLegacyLocalMemoryTemplate(),
	},
	{
		path: "scripts/codex-learn",
		render: () => renderCodexLearnTemplate(),
	},
	{
		path: "scripts/codex-enforced",
		render: () => renderCodexEnforcedTemplate(),
	},
	{
		path: "scripts/verify-work.sh",
		render: (pm) => renderVerifyWorkScript(pm),
	},
	{
		path: "scripts/validate-codestyle.sh",
		render: () => renderValidateCodestyleScript(),
	},
	{
		path: "scripts/check-codestyle-parity.sh",
		render: () => renderCheckCodestyleParityScript(),
	},
	{
		path: "scripts/prepare-worktree.sh",
		render: (pm) => renderPrepareWorktreeScript(pm),
	},
	{
		path: "scripts/new-task.sh",
		render: () => renderNewTaskScript(),
	},
	{
		path: "scripts/harness-cli.sh",
		render: (pm) => renderHarnessCliWrapper(pm),
	},
	{
		path: "scripts/run-harness-gate.sh",
		render: (pm) => renderHarnessGateRunner(pm),
	},
	{
		path: "scripts/check-environment.sh",
		render: () => renderCheckEnvironmentScript(),
	},
	{
		path: CODEX_ENVIRONMENT_TEMPLATE_PATH,
		render: (pm, context) => renderCodexEnvironmentTemplate(pm, context),
	},
	{
		path: ".github/ISSUE_TEMPLATE/config.yml",
		render: (_pm, context) => renderIssueTemplateConfig(context),
	},
	{
		path: ".github/CODEOWNERS",
		render: () => renderCodeownersTemplate(),
	},
	{
		path: "Makefile",
		render: () => `# Harness Development Makefile
# Run \`make help\` to see available commands

.PHONY: help install setup preflight worktree-ready verify-work codestyle-parity codestyle hooks hooks-pre-commit hooks-pre-push hooks-commit-msg secrets-staged docs-style-changed related-tests semgrep-changed diagrams-check dev build lint docs-lint fmt typecheck test check audit secrets security clean reset ci diagrams env-check

# Default target
help: ## Show this help message
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  %-15s %s\\n", $$1, $$2}' $(MAKEFILE_LIST)

# === Setup ===

install: ## Install dependencies
	pnpm install

setup: install hooks ## Full setup: install deps and configure git hooks

preflight: ## Run repository preflight checks (required local-memory gate by default)
	@bash ./scripts/codex-preflight.sh

worktree-ready: ## Bootstrap a fresh git worktree before first push
	@bash ./scripts/prepare-worktree.sh

verify-work: ## Run canonical repo-local verification wrapper
	@bash ./scripts/verify-work.sh

codestyle-parity: ## Verify CODESTYLE pack parity checksums
	@bash ./scripts/check-codestyle-parity.sh

codestyle: ## Run fail-closed codestyle validation
	@bash ./scripts/validate-codestyle.sh

hooks: ## Setup git hooks
	node scripts/setup-git-hooks.js

hooks-pre-commit: ## Run local pre-commit gates before creating a commit
	@bash ./scripts/check-hook-critical-config-sync.sh
	$(MAKE) codestyle-parity
	pnpm lint
	pnpm docs:lint
	pnpm typecheck
	pnpm run quality:docstrings
	pnpm run quality:size
	$(MAKE) secrets-staged
	$(MAKE) docs-style-changed
	$(MAKE) related-tests

hooks-pre-push: ## Run local pre-push governance gates before pushing
	pnpm exec tsx src/cli.ts docs-gate --mode required --json
	@bash ./scripts/check-diagram-freshness.sh
	pnpm exec tsx src/cli.ts tooling-audit --path . --json
	@bash ./scripts/check-environment.sh
	$(MAKE) semgrep-changed
	$(MAKE) codestyle
	pnpm build

hooks-commit-msg: ## Validate commit message policy (use HOOK_COMMIT_MSG or MSG_FILE=/path)
	@tmp_file="$$(mktemp)"; \
	trap 'rm -f "$$tmp_file"' EXIT; \
	if [ -n "$$${"${"}HOOK_COMMIT_MSG:-}" ]; then \
		printf '%s\n' "$$${"${"}HOOK_COMMIT_MSG}" > "$$tmp_file"; \
	elif [ -n "$$${"${"}MSG_FILE:-}" ]; then \
		cat "$$${"${"}MSG_FILE}" > "$$tmp_file"; \
	else \
		echo "Usage: HOOK_COMMIT_MSG=\"feat: test\" make hooks-commit-msg or make hooks-commit-msg MSG_FILE=/path/to/commit-msg" >&2; \
		exit 2; \
	fi; \
	node scripts/validate-commit-msg.js "$$tmp_file"

secrets-staged: ## Scan staged content for secrets before committing
	pnpm run secrets:staged

docs-style-changed: ## Run Vale on staged authoritative docs only
	pnpm run docs:style:changed

related-tests: ## Run Vitest related mode for staged src implementation files
	pnpm run test:related

semgrep-changed: ## Run narrow Semgrep rules against changed src implementation files
	pnpm run semgrep:changed

diagrams-check: ## Refresh architecture diagrams when sensitive paths change and fail on drift
	@bash ./scripts/check-diagram-freshness.sh

# === Development ===

dev: ## Start development server
	pnpm dev

build: ## Build for production
	pnpm build

# === Quality ===

lint: ## Run linter
	pnpm lint

docs-lint: ## Lint markdown/docs
	pnpm docs:lint

fmt: ## Format code
	pnpm fmt

typecheck: ## Run TypeScript type checking
	pnpm typecheck

test: ## Run tests
	pnpm test

check: ## Run all required quality gates
	pnpm check

# === Security ===

audit: ## Run security audit
	pnpm audit

secrets: ## Scan for secrets with gitleaks
	@gitleaks detect --source . --verbose || (echo "Install gitleaks: brew install gitleaks" && exit 1)

security: audit secrets ## Run all security checks

# === Maintenance ===

clean: ## Clean build artifacts and caches
	rm -rf dist coverage artifacts .test-traces* .traces
	rm -rf node_modules/.cache

reset: clean ## Full reset: clean and reinstall
	pnpm install

# === CI ===

ci: ## Run CI-equivalent local checks
	pnpm check

# === Diagrams ===

diagrams: ## Generate architecture diagrams
	@bash ./scripts/refresh-diagram-context.sh --force

# === Environment ===

env-check: ## Check environment policy envelope
	@bash ./scripts/check-environment.sh
`,
	},
	{
		path: "WORKFLOW.md",
		render: (pm, context) => renderWorkflowTemplate(pm, context),
	},
];

/**
 * Selects scaffold templates applicable to the specified CI provider and init options.
 *
 * Filters the global template list by:
 * - excluding templates not supported by the chosen CI provider;
 * - when `options.minimal` is true, omitting enterprise governance templates (`.github/CODEOWNERS`, `docs/PRODUCT-PLAN.md`, `.harness/ci-required-checks.json`);
 * - skipping all `.linear/` templates when `options.minimal` is true or `options.issueTracker` is `"none"` or `"github"`;
 * - skipping any template whose path contains `ISSUE_TEMPLATE` when `options.issueTracker` is `"none"`.
 *
 * @param ciProvider - The CI provider to target; used to enable/disable provider-specific templates.
 * @param options - Init options that influence template inclusion (`minimal` and `issueTracker`).
 * @returns An array of templates that should be rendered for the given CI provider and options.
 */
export function getTemplatesForProvider(
	ciProvider: CIProvider,
	options?: InitOptions,
): Template[] {
	return TEMPLATES.filter((template) => {
		if (!isTemplateEnabledForProvider(template.path, ciProvider)) {
			return false;
		}

		// Minimal mode skips enterprise governance templates
		if (options?.minimal) {
			const minimalOmit = [
				".github/CODEOWNERS",
				"docs/PRODUCT-PLAN.md",
				".harness/ci-required-checks.json",
			];
			if (minimalOmit.includes(template.path)) {
				return false;
			}
		}

		// Issue tracker skips (linear templates are implicitly skipped in minimal mode)
		if (
			options?.minimal ||
			options?.issueTracker === "none" ||
			options?.issueTracker === "github"
		) {
			if (template.path.startsWith(".linear/")) {
				return false;
			}
		}

		if (options?.issueTracker === "none") {
			if (template.path.includes("ISSUE_TEMPLATE")) {
				return false;
			}
		}

		return true;
	});
}
