import { describe, expect, it } from "vitest";
import {
	CODEX_ENVIRONMENT_AUTOGENERATED_HEADER,
	renderCodexEnvironmentTemplate,
} from "./scaffold-codex-environment-templates.js";

describe("renderCodexEnvironmentTemplate", () => {
	it("renders setup plus inferred action commands for package scripts", () => {
		const rendered = renderCodexEnvironmentTemplate("pnpm", {
			targetDir: "/tmp/project",
			packageScripts: ["dev", "typecheck", "test:ci", "build app"],
		});

		expect(rendered).toContain(CODEX_ENVIRONMENT_AUTOGENERATED_HEADER);
		expect(rendered).toContain("mise trust --yes .mise.toml || true");
		expect(rendered).toContain("bash scripts/prepare-worktree.sh");
		expect(rendered).toContain("pnpm install");
		expect(rendered).toContain('name = "Run"');
		expect(rendered).toContain("pnpm 'dev'");
		expect(rendered).toContain('name = "Debug"');
		expect(rendered).toContain("pnpm 'typecheck'");
		expect(rendered).toContain('name = "Test"');
		expect(rendered).toContain("pnpm 'test:ci'");
		expect(rendered).toContain('name = "Script: build app"');
		expect(rendered).toContain("pnpm 'build app'");
	});

	it("renders required tool actions and missing-script fallbacks", () => {
		const rendered = renderCodexEnvironmentTemplate("npm", {
			targetDir: "/tmp/project",
			packageScripts: [],
		});

		expect(rendered).toContain('name = "Semgrep"');
		expect(rendered).toContain("command -v semgrep >/dev/null 2>&1");
		expect(rendered).toContain("[codex] no run script found in package.json");
		expect(rendered).toContain("[codex] no debug script found in package.json");
		expect(rendered).toContain("[codex] no test script found in package.json");
	});

	it("escapes generated action names for TOML", () => {
		const rendered = renderCodexEnvironmentTemplate("pnpm", {
			targetDir: "/tmp/project",
			packageScripts: ['test"quoted'],
		});

		expect(rendered).toContain('name = "Script: test\\"quoted"');
	});
});
