/**
 * Codex environment template rendering for scaffolded repositories.
 *
 * This module owns the generated `.codex/environments/environment.toml` body,
 * including action inference from package scripts and required harness tool
 * actions.
 *
 * @module lib/init/scaffold-codex-environment-templates
 */

import { REQUIRED_CODEX_TOOL_ACTIONS } from "../policy/tooling-baseline.js";
import { renderInstallCommand } from "./scaffold-shell-templates.js";
import type {
	CodexAction,
	CodexActionIcon,
	TemplateRenderContext,
} from "./types.js";

/** Header used to mark harness-owned Codex environment files as autogenerated. */
export const CODEX_ENVIRONMENT_AUTOGENERATED_HEADER =
	"# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY";

/**
 * Render the Codex local-environment TOML for the repository.
 *
 * Produces a TOML document that contains a setup script, standard
 * Tools/Run/Debug/Test actions, required Codex tool actions, and one action per
 * package script discovered in the render context.
 *
 * @param packageManager - Package manager identifier used to render commands.
 * @param context - Template render context with package scripts and metadata.
 * @returns Complete TOML content for the Codex local environment file.
 */
export function renderCodexEnvironmentTemplate(
	packageManager: string,
	context: TemplateRenderContext,
): string {
	const installCommand = renderCodexInstallCommand(packageManager);
	const runScript = pickScriptForIcon(context.packageScripts, "run");
	const debugScript = pickScriptForIcon(context.packageScripts, "debug");
	const testScript = pickScriptForIcon(context.packageScripts, "test");
	const actions: CodexAction[] = [
		{
			name: "Tools",
			icon: "tool",
			command: `set -euo pipefail

${installCommand}`,
		},
		{
			name: "Run",
			icon: "run",
			command: renderScriptOrMissingCommand(packageManager, runScript, "run"),
		},
		{
			name: "Debug",
			icon: "debug",
			command: renderScriptOrMissingCommand(
				packageManager,
				debugScript,
				"debug",
			),
		},
		{
			name: "Test",
			icon: "test",
			command: renderScriptOrMissingCommand(packageManager, testScript, "test"),
		},
		...renderRequiredToolActions(),
		...renderPackageScriptActions(packageManager, context.packageScripts),
	];

	return `${CODEX_ENVIRONMENT_AUTOGENERATED_HEADER}
version = 1
name = "harness local environment"

[setup]
script = '''
set -euo pipefail

${installCommand}
'''

${actions.map((action) => renderCodexActionBlock(action)).join("\n\n")}
`;
}

function renderCodexInstallCommand(packageManager: string): string {
	return `if command -v mise >/dev/null 2>&1; then
  mise trust --yes .mise.toml || true
  mise install
fi
if [[ -f scripts/prepare-worktree.sh ]]; then
  bash scripts/prepare-worktree.sh
else
  ${renderInstallCommand(packageManager)}
fi`;
}

function renderRequiredToolActions(): CodexAction[] {
	return REQUIRED_CODEX_TOOL_ACTIONS.map((action) => ({
		name: action.name,
		icon: action.icon,
		command: `set -euo pipefail

${action.command}`,
	}));
}

function renderPackageScriptActions(
	packageManager: string,
	packageScripts: readonly string[],
): CodexAction[] {
	return packageScripts.map((script) => ({
		name: `Script: ${script}`,
		icon: inferScriptIcon(script),
		command: renderScriptActionCommand(packageManager, script),
	}));
}

function renderScriptOrMissingCommand(
	packageManager: string,
	script: string | null,
	actionType: string,
): string {
	return script
		? renderScriptActionCommand(packageManager, script)
		: renderMissingScriptActionCommand(actionType);
}

function scriptContainsToken(scriptName: string, token: string): boolean {
	const lower = scriptName.toLowerCase();
	return (
		lower === token ||
		lower.startsWith(`${token}:`) ||
		lower.endsWith(`:${token}`) ||
		lower.includes(`:${token}:`)
	);
}

function inferScriptIcon(scriptName: string): CodexActionIcon {
	const testTokens = ["test", "spec", "e2e", "integration", "unit", "coverage"];
	if (testTokens.some((token) => scriptContainsToken(scriptName, token))) {
		return "test";
	}

	const runTokens = ["dev", "start", "serve", "preview", "watch"];
	if (runTokens.some((token) => scriptContainsToken(scriptName, token))) {
		return "run";
	}

	const debugTokens = [
		"debug",
		"check",
		"lint",
		"typecheck",
		"verify",
		"validate",
		"doctor",
		"preflight",
	];
	if (debugTokens.some((token) => scriptContainsToken(scriptName, token))) {
		return "debug";
	}

	return "tool";
}

function renderMissingScriptActionCommand(actionType: string): string {
	return `set -euo pipefail

echo "[codex] no ${actionType} script found in package.json"
exit 1`;
}

function renderScriptActionCommand(
	packageManager: string,
	script: string,
): string {
	return `set -euo pipefail

${renderPackageScriptCommand(packageManager, shellEscapeArg(script))}`;
}

function pickScriptForIcon(
	packageScripts: readonly string[],
	icon: CodexActionIcon,
): string | null {
	return (
		packageScripts.find((script) => inferScriptIcon(script) === icon) ?? null
	);
}

function renderPackageScriptCommand(
	packageManager: string,
	script: string,
): string {
	if (packageManager === "yarn") {
		return `yarn ${script}`;
	}
	if (packageManager === "npm") {
		return `npm run ${script}`;
	}
	return `${packageManager} ${script}`;
}

function shellEscapeArg(value: string): string {
	return `'${value.split("'").join(`'"'"'`)}'`;
}

function escapeTomlString(value: string): string {
	return value.split("\\").join("\\\\").split('"').join('\\"');
}

function renderCodexActionBlock(action: CodexAction): string {
	return `[[actions]]
name = "${escapeTomlString(action.name)}"
icon = "${action.icon}"
command = '''
${action.command}
'''`;
}
