/**
 * Workflow scaffold renderer for `harness init`.
 *
 * This module owns the generated `WORKFLOW.md` policy and Symphony bootstrap
 * document so the scaffold registry only supplies command/context inputs.
 *
 * @module lib/init/scaffold-workflow-template
 */

import type { TemplateRenderContext } from "./types.js";

/**
 * Inputs required to render the scaffolded workflow document.
 */
export interface ScaffoldWorkflowTemplateOptions {
	checkCommand: string;
	context: TemplateRenderContext;
	installCommand: string;
}

function shellEscapeArg(value: string): string {
	return `'${value.split("'").join(`'"'"'`)}'`;
}

function renderTrackerBlock(context: TemplateRenderContext): string {
	const projectSlug = context.linearProjectSlug || "<your-project-slug>";
	const trackerKind = context.issueTracker ?? "linear";
	if (trackerKind === "linear") {
		return `tracker:
  kind: linear
  api_key: $LINEAR_API_KEY
  project_slug: "${projectSlug}"
  active_states:
    - Todo
    - In Progress
  terminal_states:
    - Done
    - Canceled
    - Duplicate`;
	}
	if (trackerKind === "github") {
		return `tracker:
  kind: github
  active_states:
    - OPEN
  terminal_states:
    - MERGED
    - CLOSED`;
	}
	return `tracker:
  kind: none`;
}

function renderTransitionRows(
	context: TemplateRenderContext,
	checkCommand: string,
): string {
	const trackerKind = context.issueTracker ?? "linear";
	if (trackerKind === "linear") {
		return `| \`S0 TODO\` | \`claim\` | preflight passes | \`harness linear claim --issue <LK> --branch <codex/...>\` | \`S1 IN_PROGRESS\` |
| \`S1 IN_PROGRESS\` | \`advance\` | \`${checkCommand}\` passes | \`harness linear handoff --issue <LK> --pr-url <url> --evidence-urls <url>\` | \`S2 IN_REVIEW\` |
| \`S1 IN_PROGRESS\` | \`blocked\` | dependency unavailable | emit unblock payload | \`S4 BLOCKED\` |
| \`S1 IN_PROGRESS\` | \`error\` | unrecoverable runtime/policy issue | record failure artifact | \`S5 FAIL\` |
| \`S2 IN_REVIEW\` | \`approved\` | review and CI pass | \`harness linear close --issue <LK> --pr-url <url>\` | \`S3 DONE\` |
| \`S2 IN_REVIEW\` | \`rejected\` | review gate fails | route back to working | \`S1 IN_PROGRESS\` |
| \`S4 BLOCKED\` | \`unblocked\` | dependency restored | resume execution | \`S1 IN_PROGRESS\` |`;
	}
	return `| \`S0 TODO\` | \`claim\` | preflight passes | create branch/worktree and start implementation | \`S1 IN_PROGRESS\` |
| \`S1 IN_PROGRESS\` | \`advance\` | \`${checkCommand}\` passes | open PR and attach validation evidence | \`S2 IN_REVIEW\` |
| \`S1 IN_PROGRESS\` | \`blocked\` | dependency unavailable | emit unblock payload | \`S4 BLOCKED\` |
| \`S1 IN_PROGRESS\` | \`error\` | unrecoverable runtime/policy issue | record failure artifact | \`S5 FAIL\` |
| \`S2 IN_REVIEW\` | \`approved\` | review and CI pass | merge PR and record closeout evidence | \`S3 DONE\` |
| \`S2 IN_REVIEW\` | \`rejected\` | review gate fails | route back to working | \`S1 IN_PROGRESS\` |
| \`S4 BLOCKED\` | \`unblocked\` | dependency restored | resume execution | \`S1 IN_PROGRESS\` |`;
}

function renderWorkflowConfig(
	options: ScaffoldWorkflowTemplateOptions,
): string {
	const repoUrl = options.context.repoUrl || "$SOURCE_REPO_URL";
	const renderedRepoUrl =
		repoUrl === "$SOURCE_REPO_URL" ? repoUrl : shellEscapeArg(repoUrl);
	return `---
# Symphony Workflow Configuration
# Generated by harness init — customize values below for your project.
${renderTrackerBlock(options.context)}
workspace:
  root: $SYMPHONY_WORKSPACE_ROOT
hooks:
  after_create: |
    git clone --depth 1 ${renderedRepoUrl} .
    ${options.installCommand}
    if ! mise trust --yes .mise.toml >/dev/null 2>&1; then
      echo "[symphony] failed to trust .mise.toml"
      echo "[symphony] Fix: run 'mise trust --yes .mise.toml' and retry"
      exit 1
    fi
    mise_trust_status="$(mise trust --show .mise.toml 2>/dev/null || true)"
    if ! printf '%s\n' "$mise_trust_status" | grep -Eq '(^|[[:space:]])[^[:space:]]+:[[:space:]]+trusted($|[[:space:]])'; then
      echo "[symphony] mise config is not trusted"
      echo "[symphony] Fix: run 'mise trust --yes .mise.toml' and retry"
      exit 1
    fi
  after_run: |
    cd "$SYMPHONY_WORKSPACE_ROOT" && rm -rf node_modules
agent:
  max_concurrent_agents: 3
  max_turns: 12
codex:
  command: "\${CODEX_BIN:-codex} app-server"
  approval_policy: on-request
  thread_sandbox: workspace-write
---
`;
}

function renderWorkflowBody(options: ScaffoldWorkflowTemplateOptions): string {
	const projectName = options.context.projectName || "<project-name>";
	const transitionRows = renderTransitionRows(
		options.context,
		options.checkCommand,
	);

	return `
# ${projectName} Workflow

## Table of Contents
- [Abbreviations](#abbreviations)
- [Metadata](#metadata)
- [Invariants](#invariants)
- [States](#states)
- [Transition Table (Canonical)](#transition-table-canonical)
- [Error Handling](#error-handling)
- [Idempotency](#idempotency)
- [Execution Modes](#execution-modes)
- [Dry-Run Simulation](#dry-run-simulation)
- [Observability Logs](#observability-logs)
- [Validation Checklist](#validation-checklist)

## Abbreviations
| Abbr | Meaning |
| --- | --- |
| \`S\` | state |
| \`E\` | event |
| \`G\` | guard |
| \`A\` | action |
| \`N\` | next state |

## Metadata
| Field | Value |
| --- | --- |
| \`owner\` | <owner> |
| \`max_duration\` | 60m |
| \`escalation\` | <escalation-path> |
| \`change_class\` | behavior |

## Invariants
| Field | Value |
| --- | --- |
| \`test_mode\` | tdd-required |
| \`test_tier\` | integration |
| \`tracer_bullet_first\` | yes |
| \`red_evidence_required\` | yes |

## States
\`\`\`txt
S0 TODO (non-terminal)
S1 IN_PROGRESS (non-terminal)
S2 IN_REVIEW (non-terminal)
S3 DONE (terminal)
S4 BLOCKED (non-terminal)
S5 FAIL (terminal)
\`\`\`

## Transition Table (Canonical)
\`S | E | G | A | N\`

| S | E | G | A | N |
| --- | --- | --- | --- | --- |
${transitionRows}

## Error Handling
- \`VALIDATION_ERROR\`: invalid input, malformed data, or missing required fields.
- \`BLOCKED_DEPENDENCY\`: missing auth/secret/permission; route to BLOCKED.
- \`POLICY_FAIL\`: required checks, policy, or gate failures.
- \`SYSTEM_ERROR\`: CLI/runtime/network failure; emit failed command.

## Idempotency
- Idempotency key: \`{{workflow_id}}|{{event}}|{{from_state}}|{{correlation_id}}\`.
- Replayed events with same key must no-op or upsert only.
- Side effects must be guarded against duplication.

## Execution Modes
- \`STRICT\`: hard-fail on validation/policy violations.
- \`ADVISORY\`: emit warnings and continue for non-safety violations.

## Dry-Run Simulation
- Dry-run has no side effects.
- Dry-run emits deterministic transition trace output.
- Output includes selected transition row and guard evaluation.

## Observability Logs
\`\`\`json
{
  "workflow_id": "{{WORKFLOW_ID}}",
  "transition_code": "S0:claim",
  "from_state": "S0 TODO",
  "to_state": "S1 IN_PROGRESS",
  "correlation_id": "{{CORRELATION_FORMAT}}",
  "result": "success|blocked|failed"
}
\`\`\`

## Validation Checklist
- [ ] canonical \`S | E | G | A | N\` table exists
- [ ] 5 non-empty cells in each transition row
- [ ] all required error codes are present
- [ ] \`STRICT\` and \`ADVISORY\` modes are declared
- [ ] dry-run semantics include no side effects and deterministic trace output
- [ ] required observability log fields are present
- [ ] \`change_class\` metadata is declared
- [ ] validation contract fields are declared
- [ ] behavior-changing workflows include TDD or reviewed exemption metadata
- [ ] tracker-specific workflow actions are wired into transition actions
`;
}

/**
 * Produce a Symphony workflow configuration and companion workflow document.
 *
 * @param options - Workflow command and repository context inputs.
 * @returns The complete scaffolded `WORKFLOW.md` content.
 */
export function renderWorkflowTemplate(
	options: ScaffoldWorkflowTemplateOptions,
): string {
	return `${renderWorkflowConfig(options)}${renderWorkflowBody(options)}`;
}
