/**
 * Render the package-command wrapper used by hook leaf adapters.
 *
 * @returns Shell contents for `scripts/run-package-command.sh`.
 */
// biome-ignore-all lint/suspicious/noTemplateCurlyInString: this template intentionally emits literal Bash parameter expansion placeholders.
export function renderRunPackageCommandScript(): string {
	return [
		"#!/usr/bin/env bash",
		"set -euo pipefail",
		"",
		'repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"',
		'cd "$repo_root"',
		"",
		'if [[ "$#" -lt 1 ]]; then',
		'	echo "Usage: bash scripts/run-package-command.sh <command> [args...]" >&2',
		"	exit 2",
		"fi",
		"",
		'command_name="$1"',
		"shift",
		"",
		"mise_tool_name() {",
		'\tcase "$1" in',
		"\t\tpython3)",
		"\t\t\tprintf '%s\\n' \"python\"",
		"\t\t\t;;",
		"\t\t*)",
		"\t\t\tprintf '%s\\n' \"$1\"",
		"\t\t\t;;",
		"\tesac",
		"}",
		"",
		"mise_tool_is_managed() {",
		'\tlocal tool_name=""',
		'\ttool_name="$(mise_tool_name "$1")"',
		'\tlocal line=""',
		'\tlocal key=""',
		"\twhile IFS= read -r line; do",
		`\t\tline="\${line%%#*}"`,
		'\t\t[[ "$line" == *"="* ]] || continue',
		`\t\tkey="\${line%%=*}"`,
		`\t\tkey="\${key#"\${key%%[![:space:]]*}"}"`,
		`\t\tkey="\${key%"\${key##*[![:space:]]}"}"`,
		'\t\tkey="${key%\\"}"',
		'\t\tkey="${key#\\"}"',
		'\t\tkey="${key%\\\'}"',
		'\t\tkey="${key#\\\'}"',
		'\t\tif [[ "$key" == "$tool_name" ]]; then',
		"\t\t\treturn 0",
		"\t\tfi",
		'\tdone <"$repo_root/.mise.toml"',
		"\treturn 1",
		"}",
		"",
		"prepend_mise_tool_paths() {",
		'\t[[ -f "$repo_root/.mise.toml" ]] || return 0',
		'\tmise_tool_is_managed "$command_name" || return 0',
		"\tif ! command -v mise >/dev/null 2>&1; then",
		'\t\techo "Error: .mise.toml is present but mise is not installed or not on PATH" >&2',
		"\t\texit 127",
		"\tfi",
		"",
		'\tlocal node_path=""',
		'\tlocal command_path=""',
		'\tif ! node_path="$(mise --cd "$repo_root" which node 2>/dev/null)"; then',
		"\t\techo \"Error: mise could not resolve pinned tool 'node' from .mise.toml\" >&2",
		'\t\techo "Fix: trust this repo with mise and install pinned tools, then retry." >&2',
		"\t\texit 127",
		"\tfi",
		'\tif ! command_path="$(mise --cd "$repo_root" which "$command_name" 2>/dev/null)"; then',
		"\t\techo \"Error: mise could not resolve pinned tool '$command_name' from .mise.toml\" >&2",
		'\t\techo "Fix: trust this repo with mise and install pinned tools, then retry." >&2',
		"\t\texit 127",
		"\tfi",
		"",
		'\tif [[ -z "$node_path" || ! -x "$node_path" ]]; then',
		'\t\techo "Error: mise resolved node to a non-executable path: $node_path" >&2',
		"\t\texit 127",
		"\tfi",
		'\tif [[ -z "$command_path" || ! -e "$command_path" ]]; then',
		"\t\techo \"Error: mise resolved '$command_name' to a missing path: $command_path\" >&2",
		"\t\texit 127",
		"\tfi",
		"",
		'\tPATH="$(dirname "$node_path"):$(dirname "$command_path"):$PATH"',
		"\texport PATH",
		"}",
		"",
		"prepend_mise_tool_paths",
		"",
		'if ! command -v "$command_name" >/dev/null 2>&1; then',
		"\techo \"Error: required command '$command_name' is not installed or not on PATH\" >&2",
		"\texit 127",
		"fi",
		"",
		'exec "$command_name" "$@"',
		"",
	].join("\n");
}
