flowchart TD
  subgraph Channels["Event channels / queues"]
    replay_ac203c98{{"replay"}}
    pilot_rollback_00c1f82c{{"pilot-rollback"}}
    pilot_rollback_test_e61d5a2b{{"pilot-rollback.test"}}
    pilot_evaluate_test_a2ac06fc{{"pilot-evaluate.test"}}
    init_bb54068a{{"init"}}
    tracer_1e6243a2{{"tracer"}}
    types_5_f869ec4b{{"types"}}
    mutation_queue_ce5a530e{{"mutation-queue"}}
    mutation_queue_test_10b599e8{{"mutation-queue.test"}}
  end
  classDef eventNode fill:#db2777,color:#fff