/**
 * harness linear sync
 *
 * Promotes harness gate findings into Linear issues idempotently.
 * Same finding (same fingerprint) synced twice updates the existing issue
 * instead of creating a duplicate.
 *
 * Fingerprint strategy: deterministic SHA-256 of `${team}:${checkId}:${title}`
 * stored as a Linear label "harness-sync:<fingerprint[:8]>" on the created issue.
 * On sync, we search for issues with that label before creating a new one.
 *
 * Usage:
 *   harness linear sync --findings <path|-> --team <key> [--dry-run] [--json]
 */

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { sanitizeError } from "../lib/input/sanitize.js";
import type {
	LinearCreatedIssueSummary,
	LinearIssueSummary,
} from "../lib/linear/client.js";
import { LinearAPIError, LinearClient } from "../lib/linear/client.js";
import { normalizeToken } from "../lib/linear/utils.js";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface HarnessFinding {
	/** Stable check identifier, e.g. "drift-gate:command.surface.sources.missing" */
	id: string;
	/** Short human title */
	title: string;
	/** Severity: error | warn | info */
	severity?: string;
	/** Markdown description / reproduction context */
	description?: string;
	/** Fix command(s) the agent can run */
	fixCommands?: string[];
	/** Evidence file paths or URLs */
	evidenceUrls?: string[];
	/** Source gate that emitted this finding */
	gate?: string;
}

export interface LinearSyncOptions {
	/** Path to findings JSON (or "-" for stdin) */
	findings?: string;
	/** Inline findings array (for programmatic use) */
	findingsData?: HarnessFinding[];
	/** Linear team key/name to create issues in */
	team?: string;
	/** Linear API token (falls back to LINEAR_API_KEY env var) */
	token?: string;
	/** Preview changes without writing to Linear */
	dryRun?: boolean;
	/** Output JSON */
	json?: boolean;
}

export type SyncAction = "created" | "updated" | "skipped";

export interface SyncResult {
	finding: HarnessFinding;
	action: SyncAction;
	issue?: {
		identifier: string;
		title: string;
		url: string;
	};
	skippedReason?: string;
}

export type LinearSyncResult =
	| { ok: true; results: SyncResult[]; dryRun: boolean }
	| { ok: false; error: { code: string; message: string } };

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Stable 8-char short fingerprint for a finding in a team. */
function fingerprintFinding(teamKey: string, finding: HarnessFinding): string {
	const raw = `${teamKey.toLowerCase()}:${finding.id}:${finding.title}`;
	return createHash("sha256").update(raw).digest("hex").slice(0, 8);
}

/** Label name we stamp on managed issues so we can find them later. */
function syncLabelName(fingerprint: string): string {
	return `harness-sync:${fingerprint}`;
}

/** Build the Linear issue description body from a finding. */
function buildIssueDescription(finding: HarnessFinding): string {
	const lines: string[] = [];

	if (finding.description?.trim()) {
		lines.push(finding.description.trim());
		lines.push("");
	}

	if (finding.fixCommands && finding.fixCommands.length > 0) {
		lines.push("## Fix");
		for (const cmd of finding.fixCommands) {
			lines.push(`\`\`\`\n${cmd}\n\`\`\``);
		}
		lines.push("");
	}

	if (finding.evidenceUrls && finding.evidenceUrls.length > 0) {
		lines.push("## Evidence");
		for (const url of finding.evidenceUrls) {
			lines.push(`- ${url}`);
		}
		lines.push("");
	}

	lines.push("---");
	lines.push(
		`_Generated by \`harness linear sync\` from gate \`${finding.gate ?? "unknown"}\`._`,
	);
	if (finding.severity) {
		lines.push(`_Severity: ${finding.severity}_`);
	}
	lines.push(`_Finding ID: \`${finding.id}\`_`);

	return lines.join("\n");
}

/** Map finding severity to Linear priority (0=none,1=urgent,2=high,3=normal,4=low). */
function severityToPriority(severity: string | undefined): number {
	switch (severity) {
		case "error":
			return 2; // High
		case "warn":
			return 3; // Normal
		default:
			return 4; // Low
	}
}

/** Load findings from a file path, "-" for stdin, or inline array. */
function loadFindings(options: LinearSyncOptions): HarnessFinding[] {
	if (options.findingsData) {
		return options.findingsData;
	}
	const source = options.findings?.trim();
	if (!source) {
		throw new Error("No findings source provided. Use --findings <path|->.");
	}
	let raw: string;
	if (source === "-") {
		raw = readFileSync("/dev/stdin", "utf8");
	} else {
		raw = readFileSync(source, "utf8");
	}
	const parsed: unknown = JSON.parse(raw);
	if (!Array.isArray(parsed)) {
		throw new Error("Findings JSON must be an array of finding objects.");
	}
	return parsed as HarnessFinding[];
}

// ---------------------------------------------------------------------------
// Core sync logic
// ---------------------------------------------------------------------------

/**
 * Find an existing Linear issue that was previously created by harness sync
 * for this fingerprint. We look for issues with the harness-sync label.
 */
async function findExistingIssue(
	client: LinearClient,
	labelName: string,
): Promise<LinearIssueSummary | undefined> {
	// Search by the exact label name — Linear search supports label: filters
	const results = await client.searchIssues(labelName);
	return results.find(
		(issue) =>
			// Extra guard: the issue title must contain the label name in search results.
			// Linear's search is fuzzy, so we resolve issues whose searchIssues returns
			// the label string. We rely on the label being sufficiently unique (hash).
			issue.identifier !== undefined,
	);
}

/**
 * Ensure the harness-sync label exists for the team, creating it if missing.
 * Returns the label ID.
 */
async function ensureLabel(
	client: LinearClient,
	teamId: string,
	labelName: string,
	dryRun: boolean,
): Promise<string | undefined> {
	const existing = await client.listLabels(teamId);
	const found = existing.find((l) => l.name === labelName);
	if (found) {
		return found.id;
	}
	if (dryRun) {
		return undefined; // Don't create labels in dry-run
	}
	// Linear doesn't expose a labelCreate mutation in the basic schema;
	// we'll attach the label by name via issue create — Linear auto-creates
	// workspace labels. We skip ID-based lookup and rely on name matching.
	return undefined;
}

export async function runLinearSync(
	options: LinearSyncOptions,
): Promise<LinearSyncResult> {
	const token =
		normalizeToken(options.token) ?? normalizeToken(process.env.LINEAR_API_KEY);
	if (!token) {
		return {
			ok: false,
			error: {
				code: "VALIDATION_ERROR",
				message:
					"Missing Linear API key. Provide --token or set LINEAR_API_KEY.",
			},
		};
	}

	let findings: HarnessFinding[];
	try {
		findings = loadFindings(options);
	} catch (error) {
		return {
			ok: false,
			error: {
				code: "VALIDATION_ERROR",
				message: `Failed to load findings: ${sanitizeError(error)}`,
			},
		};
	}

	if (findings.length === 0) {
		return { ok: true, results: [], dryRun: options.dryRun ?? false };
	}

	const client = new LinearClient({ token });

	try {
		// Resolve team
		const teams = await client.listTeams();
		const teamKey = options.team?.trim().toLowerCase();
		const team = teamKey
			? teams.find(
					(t) =>
						t.key.toLowerCase() === teamKey || t.name.toLowerCase() === teamKey,
				)
			: teams[0];

		if (!team) {
			return {
				ok: false,
				error: {
					code: "NOT_FOUND",
					message: `Team not found: ${options.team ?? "(none — no teams available)"}`,
				},
			};
		}

		const results: SyncResult[] = [];
		const dryRun = options.dryRun ?? false;

		for (const finding of findings) {
			const fingerprint = fingerprintFinding(team.key, finding);
			const labelName = syncLabelName(fingerprint);

			// Check for existing issue
			const existing = await findExistingIssue(client, labelName);

			if (existing) {
				// Issue already exists — add an update comment with latest context
				if (!dryRun) {
					const commentBody = [
						`**Harness sync update** — finding \`${finding.id}\` still active.`,
						"",
						finding.description?.trim() ?? "",
						"",
						finding.fixCommands?.length
							? `Fix: \`${finding.fixCommands[0]}\``
							: "",
					]
						.filter((l) => l !== undefined)
						.join("\n")
						.trim();

					await client.createComment(existing.identifier, commentBody);
					await client.updateIssue(existing.identifier, {
						// Re-raise priority if it's been lowered
						priority: severityToPriority(finding.severity),
					});
				}

				results.push({
					finding,
					action: "updated",
					issue: {
						identifier: existing.identifier,
						title: existing.title,
						url: existing.url,
					},
				});
			} else {
				// Create new issue
				let created: LinearCreatedIssueSummary | undefined;

				if (!dryRun) {
					await ensureLabel(client, team.id, labelName, dryRun);
					created = await client.createIssue({
						teamId: team.id,
						title: `[harness] ${finding.title}`,
						description: buildIssueDescription(finding),
						priority: severityToPriority(finding.severity),
					});
					// Add a comment with the sync fingerprint label so we can find
					// this issue on future syncs
					await client.createComment(
						created.identifier,
						`_harness-sync fingerprint: \`${labelName}\`_\n\nThis issue is managed by \`harness linear sync\`. Do not remove the fingerprint line.`,
					);
				}

				const entry: SyncResult = {
					finding,
					action: dryRun ? "skipped" : "created",
				};
				if (dryRun) {
					entry.skippedReason = "dry-run";
				}
				if (created) {
					entry.issue = {
						identifier: created.identifier,
						title: created.title,
						url: created.url,
					};
				}
				results.push(entry);
			}
		}

		return { ok: true, results, dryRun };
	} catch (error) {
		const safeError = sanitizeError(error);
		if (error instanceof LinearAPIError) {
			if (
				error.code === "AUTHENTICATION_REQUIRED" ||
				error.code === "FORBIDDEN" ||
				error.code === "PERMISSION_DENIED"
			) {
				return {
					ok: false,
					error: {
						code: "PERMISSION_DENIED",
						message: `Linear API permission denied: ${safeError}`,
					},
				};
			}
		}
		return {
			ok: false,
			error: {
				code: "SYSTEM_ERROR",
				message: `Linear sync failed: ${safeError}`,
			},
		};
	}
}

// ---------------------------------------------------------------------------
// CLI entry point
// ---------------------------------------------------------------------------

export async function runLinearSyncCLI(
	options: LinearSyncOptions,
): Promise<number> {
	const result = await runLinearSync(options);

	if (!result.ok) {
		if (options.json) {
			console.error(
				JSON.stringify({ ok: false, error: result.error }, null, 2),
			);
		} else {
			console.error(`Error: ${result.error.message}`);
		}
		switch (result.error.code) {
			case "VALIDATION_ERROR":
				return 1;
			case "NOT_FOUND":
				return 2;
			case "PERMISSION_DENIED":
				return 3;
			default:
				return 10;
		}
	}

	const { results, dryRun } = result;
	const created = results.filter((r) => r.action === "created").length;
	const updated = results.filter((r) => r.action === "updated").length;
	const skipped = results.filter((r) => r.action === "skipped").length;

	if (options.json) {
		console.info(
			JSON.stringify(
				{
					ok: true,
					dryRun,
					summary: { total: results.length, created, updated, skipped },
					results,
				},
				null,
				2,
			),
		);
	} else {
		const prefix = dryRun ? "[dry-run] " : "";
		console.info(
			`${prefix}Synced ${results.length} finding(s): ${created} created, ${updated} updated, ${skipped} skipped`,
		);
		for (const r of results) {
			const issueRef = r.issue ? ` → ${r.issue.identifier} ${r.issue.url}` : "";
			const skipNote = r.skippedReason ? ` (${r.skippedReason})` : "";
			console.info(`  [${r.action}]${skipNote} ${r.finding.title}${issueRef}`);
		}
	}

	return 0;
}
