import type {
	CommandAgentMode,
	CommandCategory,
	CommandOrchestrator,
	CommandPrimaryAudience,
	CommandRetryability,
	CommandTier,
} from "./command-capabilities.js";
import {
	AGENT_NATIVE_ORIENT_COMMAND_NAMES,
	AGENT_NATIVE_PACKET_COMMAND_NAMES,
	mapCommands,
} from "./command-agent-native-capability-rules.js";

export { EXPECTED_ARTIFACTS_BY_NAME } from "./command-expected-artifacts.js";
export { REQUIRED_FLAGS_BY_NAME } from "./command-required-flags.js";
export { COMMAND_VISIBILITY_BY_NAME } from "./command-visibility-rules.js";

export const COMMAND_CATEGORY_BY_NAME: Partial<
	Record<string, CommandCategory>
> = {
	commands: "discovery",
	orient: "bootstrap-governance",
	"agent-readiness": "bootstrap-governance",
	init: "bootstrap-governance",
	"fleet-plan": "bootstrap-governance",
	eject: "bootstrap-governance",
	check: "bootstrap-governance",
	next: "bootstrap-governance",
	...(mapCommands(
		AGENT_NATIVE_PACKET_COMMAND_NAMES,
		"bootstrap-governance",
	) as Partial<Record<string, CommandCategory>>),
	doctor: "bootstrap-governance",
	audit: "bootstrap-governance",
	brain: "bootstrap-governance",
	health: "bootstrap-governance",
	contract: "bootstrap-governance",
	upgrade: "bootstrap-governance",
	"ci-migrate": "bootstrap-governance",
	"branch-protect": "bootstrap-governance",
	"verify-work": "bootstrap-governance",
	"verify-coderabbit": "bootstrap-governance",
	preset: "bootstrap-governance",
	"symphony-check": "bootstrap-governance",
	"policy-gate": "review-policy",
	"decision-request": "review-policy",
	"preflight-gate": "review-policy",
	"review-gate": "review-policy",
	"docs-gate": "review-policy",
	"plan-gate": "review-policy",
	"brainstorm-gate": "review-policy",
	"prompt-gate": "review-policy",
	"pr-closeout": "review-policy",
	"pr-template-gate": "review-policy",
	"rule-lifecycle-gate": "review-policy",
	"license-gate": "review-policy",
	"check-authz": "review-policy",
	"check-environment": "review-policy",
	"local-memory-preflight": "review-policy",
	"artifact-gate": "review-policy",
	"artifact-routine": "review-policy",
	"runtime-budget": "review-policy",
	"ci-ownership-gate": "review-policy",
	"blast-radius": "review-policy",
	"risk-tier": "review-policy",
	"pattern-scope": "review-policy",
	"diff-budget": "review-policy",
	"observability-gate": "review-policy",
	"silent-error": "review-policy",
	"memory-gate": "review-policy",
	linear: "workflow-linear",
	"linear-gate": "workflow-linear",
	"workflow:generate": "workflow-linear",

	"pilot-evaluate": "pilot-remediation",
	"pilot-rollback": "pilot-remediation",
	simulate: "pilot-remediation",
	"automation-run": "pilot-remediation",
	"gap-case": "pilot-remediation",
	remediate: "pilot-remediation",
	replay: "pilot-remediation",
	"drift-gate": "drift-search-evidence",
	"org-audit": "drift-search-evidence",
	"tooling-audit": "drift-search-evidence",
	"feedback-loop-audit": "drift-search-evidence",
	gardener: "drift-search-evidence",
	"context-health": "drift-search-evidence",
	"prompt-context-drift:write": "drift-search-evidence",
	"prompt-context-drift:validate": "drift-search-evidence",
	learnings: "drift-search-evidence",
	"north-star-feedback": "drift-search-evidence",
	"review-context": "drift-search-evidence",
	"validation-plan": "drift-search-evidence",
	fitness: "drift-search-evidence",
	search: "drift-search-evidence",
	context: "drift-search-evidence",
	"source-outline": "drift-search-evidence",
	"index-context": "drift-search-evidence",
	"evidence-verify": "drift-search-evidence",
	"ui:fast": "drift-search-evidence",
	"ui:verify": "drift-search-evidence",
	"ui:explore": "drift-search-evidence",
};

export const WRITE_COMMANDS = new Set<string>([
	"init",
	"eject",
	"upgrade",
	"ci-migrate",
	"branch-protect",
	"linear",
	"linear-gate",
	"automation-run",
	"gap-case",
	"remediate",
	"pilot-rollback",
	"learnings",
	"prompt-context-drift:write",
]);

export const RETRYABILITY_BY_NAME: Partial<
	Record<string, CommandRetryability>
> = {
	commands: "safe",
	orient: "safe",
	"agent-readiness": "safe",
	check: "safe",
	next: "safe",
	"pr-closeout": "safe",
	"decision-request": "safe",
	...(mapCommands(AGENT_NATIVE_PACKET_COMMAND_NAMES, "safe") as Partial<
		Record<string, CommandRetryability>
	>),
	"prompt-context-drift:write": "safe",
	"prompt-context-drift:validate": "safe",
	"runtime-budget": "safe",
	"fleet-plan": "safe",
	doctor: "safe",
	health: "safe",
	audit: "safe",
	brain: "safe",
	contract: "safe",
	"check-environment": "safe",
	"check-authz": "safe",
	"local-memory-preflight": "safe",
	search: "safe",
	context: "safe",
	"source-outline": "safe",
	"index-context": "conditional",
	"automation-run": "manual",
	"pilot-rollback": "manual",
	"branch-protect": "manual",
};

export const SAFE_FIRST_ALTERNATIVES_BY_NAME: Partial<
	Record<string, string[]>
> = {
	init: ["init --dry-run", "check --json"],
	upgrade: ["upgrade --dry-run", "contract validate --json"],
	"ci-migrate": ["ci-migrate prepare --dry-run --json"],
	remediate: ["remediate run --json"],
	linear: ["linear prepare --issue <KEY>", "linear triage --dry-run --json"],
	"linear-gate": ["linear prepare --issue <KEY>"],
	"branch-protect": ["check-authz --json"],
	"pilot-rollback": ["pilot-evaluate --artifacts <PATH> --json"],
	"automation-run": ["check --json"],
};

export const COMMAND_TIER_BY_NAME: Partial<Record<string, CommandTier>> = {
	check: "cockpit",
	next: "cockpit",
	orient: "cockpit",
	...(mapCommands(AGENT_NATIVE_PACKET_COMMAND_NAMES, "domain") as Partial<
		Record<string, CommandTier>
	>),
	"decision-request": "domain",
	"agent-readiness": "domain",
	"fleet-plan": "domain",

	init: "domain",
	contract: "domain",
	"review-gate": "domain",
	"pr-closeout": "domain",
	"docs-gate": "domain",
	"ci-migrate": "domain",
	linear: "domain",
	"validation-plan": "domain",
	fitness: "domain",
	"review-context": "domain",
	"pattern-scope": "domain",
	"artifact-routine": "domain",
	"runtime-budget": "domain",
	"prompt-context-drift:write": "domain",
	"prompt-context-drift:validate": "domain",

	"drift-gate": "plumbing",
	"artifact-gate": "plumbing",
	"source-outline": "plumbing",
	"index-context": "plumbing",
	replay: "plumbing",
	simulate: "plumbing",
	"policy-gate": "plumbing",
	"preflight-gate": "plumbing",
	"plan-gate": "plumbing",
	"brainstorm-gate": "plumbing",
	"prompt-gate": "plumbing",
	"pr-template-gate": "plumbing",
	"rule-lifecycle-gate": "plumbing",
	"license-gate": "plumbing",
	"check-authz": "plumbing",
	"check-environment": "plumbing",
	"local-memory-preflight": "plumbing",
	"ci-ownership-gate": "plumbing",
	"blast-radius": "plumbing",
	"risk-tier": "plumbing",
	"diff-budget": "plumbing",
	"observability-gate": "plumbing",
	"silent-error": "plumbing",
	"memory-gate": "plumbing",
};

export const PRIMARY_AUDIENCE_BY_NAME: Partial<
	Record<string, CommandPrimaryAudience>
> = {
	commands: "agent",
	orient: "agent",
	"agent-readiness": "agent",
	check: "both",
	next: "agent",
	...(mapCommands(AGENT_NATIVE_PACKET_COMMAND_NAMES, "agent") as Partial<
		Record<string, CommandPrimaryAudience>
	>),
	"prompt-context-drift:write": "agent",
	"prompt-context-drift:validate": "agent",
	"decision-request": "agent",
	"fleet-plan": "agent",
	doctor: "both",
	health: "both",
	fitness: "agent",
	"review-gate": "agent",
	"pr-closeout": "agent",
	"docs-gate": "agent",
	"validation-plan": "agent",
	"review-context": "agent",
	"pattern-scope": "agent",
	"artifact-routine": "agent",
	"runtime-budget": "agent",
	"source-outline": "agent",
	"index-context": "agent",
	search: "both",
	context: "both",
	linear: "human",
};

export const ORCHESTRATED_BY_BY_NAME: Partial<
	Record<string, CommandOrchestrator[]>
> = {
	orient: [],
	next: [],
	"agent-readiness": ["next"],
	...(mapCommands(AGENT_NATIVE_PACKET_COMMAND_NAMES, ["next"]) as Partial<
		Record<string, CommandOrchestrator[]>
	>),
	"prompt-context-drift:write": ["next"],
	"prompt-context-drift:validate": ["next"],
	"fleet-plan": ["next"],
	check: ["next"],
	doctor: ["next"],
	health: ["next"],
	fitness: ["next"],
	"review-gate": ["next", "pr-ready"],
	"pr-closeout": ["next", "pr-ready"],
	"decision-request": ["next", "pr-ready"],
	"docs-gate": ["next", "pr-ready"],
	"validation-plan": ["next", "pr-ready"],
	"review-context": ["next", "pr-ready"],
	"pattern-scope": ["next", "pr-ready"],
	"artifact-routine": ["next", "pr-ready"],
	"runtime-budget": ["next", "pr-ready"],
	"linear-gate": ["pr-ready"],
	"north-star-feedback": ["learn"],
	"feedback-loop-audit": ["learn"],
	learnings: ["learn"],
};

export const AGENT_MODE_BY_NAME: Partial<Record<string, CommandAgentMode>> = {
	commands: "orient",
	orient: "orient",
	"agent-readiness": "orient",
	check: "verify",
	next: "orient",
	...(mapCommands(AGENT_NATIVE_ORIENT_COMMAND_NAMES, "orient") as Partial<
		Record<string, CommandAgentMode>
	>),
	"agent-rework": "repair",
	"reviewer-decision": "review",
	"prompt-context-drift:write": "repair",
	"prompt-context-drift:validate": "verify",
	init: "orient",
	"fleet-plan": "plan",
	doctor: "orient",
	health: "orient",
	fitness: "verify",
	contract: "verify",
	"verify-work": "verify",
	"verify-coderabbit": "review",
	"review-gate": "review",
	"pr-closeout": "handoff",
	"decision-request": "handoff",
	"docs-gate": "verify",
	"validation-plan": "verify",
	"review-context": "review",
	"pattern-scope": "review",
	"artifact-routine": "verify",
	"runtime-budget": "verify",
	"linear-gate": "handoff",
	linear: "handoff",
	remediate: "repair",
	learnings: "learn",
	"north-star-feedback": "learn",
	"feedback-loop-audit": "learn",
};
