/**
 * PR Creator
 *
 * Creates maintenance PRs for documentation gardening updates.
 * Uses GARDENER_TOKEN (personal access token) for authentication.
 */

import { throttling } from "@octokit/plugin-throttling";
import { Octokit } from "@octokit/rest";
import type { GardenerOutput } from "./types.js";

// Create Octokit with throttling plugin
const ThrottledOctokit = Octokit.plugin(throttling);

/**
 * Format date as YYYY-MM-DD
 */
function formatDate(date: Date): string {
	return date.toISOString().split("T")[0] ?? "";
}

/**
 * PR creation options
 */
export interface PRCreatorOptions {
	/** Repository owner */
	owner: string;
	/** Repository name */
	repo: string;
	/** GitHub token (GARDENER_TOKEN) */
	token: string;
	/** Base branch for PR */
	baseBranch?: string;
}

/**
 * PR creation result
 */
export interface PRCreatorResult {
	ok: true;
	prUrl: string;
	prNumber: number;
}

/**
 * PR creation error
 */
export interface PRCreatorError {
	ok: false;
	error: string;
	code: string;
}

/**
 * Get repository owner and repo from environment or git remote
 */
export function getRepoInfo(): { owner: string; repo: string } | null {
	// Try GITHUB_REPOSITORY env var first (set in GitHub Actions)
	const githubRepo = process.env.GITHUB_REPOSITORY;
	if (githubRepo) {
		const [owner, repo] = githubRepo.split("/");
		if (owner && repo) {
			return { owner, repo };
		}
	}

	// Try to parse from git remote (local development)
	// This is a simplified version - in production you might want to use git parse
	return null;
}

/**
 * Render PR body with gardening findings
 */
function renderPRBody(output: GardenerOutput): string {
	const date = formatDate(new Date());

	let body = "## 🌱 Documentation Gardening Report\n\n";
	body += `**Date:** ${date}\n\n`;

	// Quality score section
	if (output.qualityScore) {
		body += `### Quality Score: ${output.qualityScore.score}/100\n\n`;
		body += "| Category | Count | Deduction |\n";
		body += "|----------|-------|-----------|\n";
		body += `| Stale Docs | ${output.qualityScore.staleDocCount} | -${output.qualityScore.staleDeduction} |\n`;
		body += `| Broken Links | ${output.qualityScore.brokenLinkCount} | -${output.qualityScore.brokenLinkDeduction} |\n\n`;
	}

	// Stale docs section
	if (output.staleDocs.length > 0) {
		body += `### 📄 Stale Documents (${output.staleDocs.length})\n\n`;
		for (const doc of output.staleDocs.slice(0, 10)) {
			if (doc.daysSinceValidation === Number.POSITIVE_INFINITY) {
				body += `- \`${doc.path}\` - never validated\n`;
			} else {
				body += `- \`${doc.path}\` - ${doc.daysSinceValidation} days since validation\n`;
			}
		}
		if (output.staleDocs.length > 10) {
			body += `\n_...and ${output.staleDocs.length - 10} more_\n`;
		}
		body += "\n";
	}

	// Broken links section
	if (output.brokenLinks.length > 0) {
		body += `### 🔗 Broken Links (${output.brokenLinks.length})\n\n`;
		for (const link of output.brokenLinks.slice(0, 10)) {
			const status = link.statusCode ? ` [${link.statusCode}]` : "";
			body += `- **${link.file}**: ${link.link}${status}\n`;
		}
		if (output.brokenLinks.length > 10) {
			body += `\n_...and ${output.brokenLinks.length - 10} more_\n`;
		}
		body += "\n";
	}

	body += "---\n";
	body +=
		"🤖 Generated by [harness gardener](https://github.com/jscraik/coding-harness)\n";

	return body;
}

/**
 * Create a maintenance PR for gardening updates
 */
export async function createMaintenancePR(
	options: PRCreatorOptions,
	output: GardenerOutput,
	qualityScoreContent: string,
	dryRun = false,
): Promise<PRCreatorResult | PRCreatorError> {
	// Skip if no issues found or dry-run mode
	if (!output.needsPR) {
		return {
			ok: false,
			error: "No issues found - PR not needed",
			code: "NO_ISSUES",
		};
	}

	if (dryRun) {
		console.info("[DRY-RUN] Would create PR with:");
		console.info(
			`  Title: docs: gardening updates (${formatDate(new Date())})`,
		);
		console.info("  Files: docs/QUALITY_SCORE.md");
		return {
			ok: false,
			error: "Dry-run mode - PR not created",
			code: "DRY_RUN",
		};
	}

	const { owner, repo, token, baseBranch = "main" } = options;
	const branchName = `gardener/${formatDate(new Date())}`;

	try {
		const octokit = new ThrottledOctokit({
			auth: token,
			throttle: {
				onRateLimit: (retryAfter: number) => {
					console.warn(`Rate limit hit, retrying after ${retryAfter}s`);
					return true;
				},
				onSecondaryRateLimit: (retryAfter: number) => {
					console.warn(
						`Secondary rate limit hit, retrying after ${retryAfter}s`,
					);
					return true;
				},
			},
		});

		// Get the base branch's latest commit
		const { data: ref } = await octokit.rest.git.getRef({
			owner,
			repo,
			ref: `heads/${baseBranch}`,
		});

		// Create a new branch
		try {
			await octokit.rest.git.createRef({
				owner,
				repo,
				ref: `refs/heads/${branchName}`,
				sha: ref.object.sha,
			});
		} catch (_error) {
			// Branch might already exist from a previous run
			console.warn(`Branch ${branchName} may already exist, continuing...`);
		}

		// Create or update the quality score file
		const { data: currentFile } = await octokit.rest.repos
			.getContent({
				owner,
				repo,
				path: "docs/QUALITY_SCORE.md",
				ref: branchName,
			})
			.catch(() => ({ data: null }));

		const fileParams: Parameters<
			typeof octokit.rest.repos.createOrUpdateFileContents
		>[0] = {
			owner,
			repo,
			path: "docs/QUALITY_SCORE.md",
			message: `docs: update quality score (${formatDate(new Date())})`,
			content: Buffer.from(qualityScoreContent).toString("base64"),
			branch: branchName,
		};

		if (currentFile && "sha" in currentFile) {
			fileParams.sha = currentFile.sha;
		}

		await octokit.rest.repos.createOrUpdateFileContents(fileParams);

		// Create the PR
		const { data: pr } = await octokit.rest.pulls.create({
			owner,
			repo,
			title: `docs: gardening updates (${formatDate(new Date())})`,
			body: renderPRBody(output),
			head: branchName,
			base: baseBranch,
		});

		return {
			ok: true,
			prUrl: pr.html_url,
			prNumber: pr.number,
		};
	} catch (error) {
		return {
			ok: false,
			error: error instanceof Error ? error.message : "Unknown error",
			code: "PR_CREATION_FAILED",
		};
	}
}

/**
 * Check if GARDENER_TOKEN is available
 */
export function hasGardenerToken(): boolean {
	return !!process.env.GARDENER_TOKEN;
}

/**
 * Get GARDENER_TOKEN from environment
 */
export function getGardenerToken(): string | null {
	return process.env.GARDENER_TOKEN ?? null;
}
