name: security-scan

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:

permissions:
  contents: read
  pull-requests: read

jobs:
  secret-scan:
    name: security-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@c3e599b7163e8198a55467f3133db0e7b2a492cb # main
        continue-on-error: true
        with:
          path: ./
          extra_args: >-
            --results=verified,unknown
            --exclude-paths=./.trufflehog-exclude.txt

      - name: Fail on TruffleHog findings
        if: steps.trufflehog.outcome == 'failure'
        run: |
          echo "TruffleHog found secrets. See previous step output for details."
          exit 1
